/**
 * AI-generated content responsibility agreement.
 *
 * PennSync uses AI to generate clinical documentation, notes, assessments, and
 * other material. Before using the software, every user must sign off that they
 * understand they are responsible for proofreading and editing any AI-generated
 * material, and that they are responsible for — and attest to — anything they
 * submit using that material. The gate that enforces this lives in App.jsx
 * (rendered after authentication, before any app route); this module is the
 * single source of truth for the agreement's version, copy, and the pure
 * "has the protected attestation broker verified acceptance?" check so the
 * gate and its tests stay in step. Custom User fields and legacy UserActivity
 * rows are not gate authority; the application trusts only the immutable,
 * service-owned AIContentAgreementAttestation returned by the status broker.
 *
 * Bumping AI_CONTENT_AGREEMENT_VERSION invalidates prior acceptances, so a
 * material change to the responsibilities below re-prompts every user.
 */

/**
 * Current agreement version. Bump this whenever the acknowledgments below change
 * in a way that requires users to re-affirm (this forces re-acceptance).
 */
export const AI_CONTENT_AGREEMENT_VERSION = '1.0';

/** Heading shown at the top of the agreement gate. */
export const AI_CONTENT_AGREEMENT_TITLE = 'AI-Generated Content Responsibility';

/**
 * Plain-language context shown above the checkboxes. Explains what the user is
 * agreeing to before they check the individual acknowledgments.
 */
export const AI_CONTENT_AGREEMENT_INTRO =
  'PennSync uses artificial intelligence (AI) to help draft clinical documentation, ' +
  'notes, assessments, summaries, and other material. AI-generated content is a ' +
  'starting point only — it can be incomplete, inaccurate, or contain errors, and ' +
  'it is not a substitute for your professional clinical judgment. Before you can ' +
  'use PennSync, please review and accept the responsibilities below.';

/**
 * The specific acknowledgments the user must affirm. Each renders as its own
 * required checkbox in the gate; the user cannot continue until all are checked.
 * Order and wording are the audited record of what was agreed to.
 */
export const AI_CONTENT_AGREEMENT_ACKNOWLEDGMENTS = [
  'I understand that material generated by AI may be incomplete, inaccurate, or ' +
    'contain errors, and that I must not rely on it without review.',
  'I understand that I am responsible for proofreading, reviewing, and editing all ' +
    'AI-generated material before it is used or submitted.',
  'I understand that I am solely responsible for the accuracy, completeness, and ' +
    'clinical appropriateness of any material I submit, and that by submitting ' +
    'AI-generated material I attest that I have reviewed it and agree with its contents.',
];

/**
 * Whether the protected status broker verified acceptance of the CURRENT
 * agreement version. A prior acceptance of an older version does not count.
 *
 * @param {object|null|undefined} status - The broker's narrow status response.
 * @returns {boolean}
 */
export function hasAcceptedAiContentAgreement(status) {
  if (!status) return false;
  return (
    status.accepted === true &&
    status.agreement_version === AI_CONTENT_AGREEMENT_VERSION
  );
}
