import { Toaster, toast as rawToast } from 'tenant-sonner-raw';

// Sonner is process-global: a callback that began under tenant A can publish
// after tenant B is READY even though A's React tree has unmounted. Until every
// asynchronous operation carries an authority lease, never put caller-provided
// text, descriptions, JSX, ids, or action closures into that global store.
const SAFE_MESSAGES = Object.freeze({
  default: 'Notification',
  success: 'Action completed.',
  error: 'The action could not be completed.',
  info: 'Information updated.',
  warning: 'Review required.',
  loading: 'Working…',
});

const SAFE_POSITIONS = new Set([
  'top-left',
  'top-center',
  'top-right',
  'bottom-left',
  'bottom-center',
  'bottom-right',
]);

function safeOptions(options) {
  if (!options || typeof options !== 'object') return undefined;
  const safe = {};
  if (Number.isFinite(options.duration) && options.duration >= 0) {
    safe.duration = Math.min(options.duration, 60_000);
  }
  if (SAFE_POSITIONS.has(options.position)) safe.position = options.position;
  for (const key of ['closeButton', 'dismissible', 'important', 'invert']) {
    if (typeof options[key] === 'boolean') safe[key] = options[key];
  }
  return safe;
}

function toast(_message, options) {
  return rawToast(SAFE_MESSAGES.default, safeOptions(options));
}

toast.success = (_message, options) => rawToast.success(
  SAFE_MESSAGES.success,
  safeOptions(options),
);
toast.error = (_message, options) => rawToast.error(
  SAFE_MESSAGES.error,
  safeOptions(options),
);
toast.info = (_message, options) => rawToast.info(
  SAFE_MESSAGES.info,
  safeOptions(options),
);
toast.warning = (_message, options) => rawToast.warning(
  SAFE_MESSAGES.warning,
  safeOptions(options),
);
toast.message = (_message, options) => rawToast.message(
  SAFE_MESSAGES.default,
  safeOptions(options),
);
toast.loading = (_message, options) => rawToast.loading(
  SAFE_MESSAGES.loading,
  safeOptions(options),
);
toast.custom = (_jsx, options) => rawToast.info(
  SAFE_MESSAGES.info,
  safeOptions(options),
);
toast.promise = (promiseOrFactory, options) => {
  // Never call rawToast.promise: Sonner stores the caller's Promise on its
  // process-global toast history, and that Promise can retain a resolved PHI
  // response long after dismissal. Observe it outside Sonner and update using
  // only the opaque id generated by the fixed loading toast.
  const id = rawToast.loading(SAFE_MESSAGES.loading, safeOptions(options));
  let source;
  try {
    source = typeof promiseOrFactory === 'function'
      ? promiseOrFactory()
      : promiseOrFactory;
  } catch (error) {
    source = Promise.reject(error);
  }
  const observed = Promise.resolve(source);
  const updateOptions = { ...safeOptions(options), id };
  void observed.then(
    () => rawToast.success(SAFE_MESSAGES.success, updateOptions),
    () => rawToast.error(SAFE_MESSAGES.error, updateOptions),
  );
  const unwrap = () => observed;
  return typeof id === 'string' || typeof id === 'number'
    ? Object.assign(id, { unwrap })
    : { unwrap };
};
toast.dismiss = (...args) => rawToast.dismiss(...args);

export { Toaster, toast };
