import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Brain, Loader2, FileText, UserCheck, ArrowRightLeft, ListChecks,
  Sparkles, ChevronDown, ChevronUp, AlertTriangle, RefreshCw
} from "lucide-react";
import { toast } from "sonner";

import OASISAssessmentResults from "./OASISAssessmentResults";
import FollowUpIdentification from "./FollowUpIdentification";
import ReferralSuggestions from "./ReferralSuggestions";
import AutoGeneratedTasks from "./AutoGeneratedTasks";

export default function AIClinicalWorkflowPanel({ patientId, patientName }) {
  const [activeTab, setActiveTab] = useState("oasis");
  const [loading, setLoading] = useState({});
  const [results, setResults] = useState({});
  const [expanded, setExpanded] = useState(true);

  const runAnalysis = async (action) => {
    setLoading(prev => ({ ...prev, [action]: true }));
    const { data } = await base44.functions.invoke("aiClinicalWorkflowAutomation", {
      action,
      patient_id: patientId,
    });
    setResults(prev => ({ ...prev, [action]: data.data }));
    setLoading(prev => ({ ...prev, [action]: false }));
    toast.success(`${ACTION_LABELS[action]} complete`);
  };

  const runFullAnalysis = async () => {
    setLoading({ full_analysis: true });
    const { data } = await base44.functions.invoke("aiClinicalWorkflowAutomation", {
      action: "full_analysis",
      patient_id: patientId,
    });
    const d = data.data;
    setResults({
      generate_oasis: d.oasis,
      identify_followups: d.followups,
      suggest_referrals: d.referrals,
      auto_generate_tasks: d.tasks,
    });
    setLoading({});
    toast.success("Full AI clinical analysis complete");
  };

  const ACTION_LABELS = {
    generate_oasis: "OASIS Assessment",
    identify_followups: "Follow-Up Identification",
    suggest_referrals: "Referral Suggestions",
    auto_generate_tasks: "Task Automation",
  };

  const TAB_ICONS = {
    oasis: FileText,
    followups: UserCheck,
    referrals: ArrowRightLeft,
    tasks: ListChecks,
  };

  const isAnyLoading = Object.values(loading).some(Boolean);

  return (
    <Card>
      <CardHeader className="p-3 sm:p-4 pb-2">
        <div className="flex items-center justify-between gap-2">
          <CardTitle className="text-sm flex items-center gap-2">
            <Brain className="w-4 h-4 text-blue-500" />
            AI Clinical Workflow Automation
            {patientName && (
              <Badge variant="outline" className="text-[10px] font-normal">{patientName}</Badge>
            )}
          </CardTitle>
          <div className="flex gap-1.5">
            <Button
              size="sm"
              className="h-7 text-[10px] bg-blue-600 hover:bg-blue-700"
              onClick={runFullAnalysis}
              disabled={isAnyLoading}
            >
              {loading.full_analysis ? (
                <Loader2 className="w-3 h-3 mr-1 animate-spin" />
              ) : (
                <Sparkles className="w-3 h-3 mr-1" />
              )}
              Full Analysis
            </Button>
            <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setExpanded(!expanded)}>
              {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
            </Button>
          </div>
        </div>
      </CardHeader>

      {expanded && (
        <CardContent className="p-3 sm:p-4 pt-0">
          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <TabsList className="w-full grid grid-cols-4 h-auto p-0.5 mb-3">
              <TabsTrigger value="oasis" className="text-[10px] sm:text-xs py-1.5 gap-1">
                <FileText className="w-3 h-3" />
                <span className="hidden sm:inline">OASIS</span>
              </TabsTrigger>
              <TabsTrigger value="followups" className="text-[10px] sm:text-xs py-1.5 gap-1">
                <UserCheck className="w-3 h-3" />
                <span className="hidden sm:inline">Follow-Ups</span>
              </TabsTrigger>
              <TabsTrigger value="referrals" className="text-[10px] sm:text-xs py-1.5 gap-1">
                <ArrowRightLeft className="w-3 h-3" />
                <span className="hidden sm:inline">Referrals</span>
              </TabsTrigger>
              <TabsTrigger value="tasks" className="text-[10px] sm:text-xs py-1.5 gap-1">
                <ListChecks className="w-3 h-3" />
                <span className="hidden sm:inline">Tasks</span>
              </TabsTrigger>
            </TabsList>

            <TabsContent value="oasis">
              <WorkflowSection
                action="generate_oasis"
                loading={loading.generate_oasis}
                result={results.generate_oasis}
                onRun={() => runAnalysis("generate_oasis")}
                description="Generate OASIS assessment items from visit notes and patient data"
                icon={FileText}
              >
                {results.generate_oasis && <OASISAssessmentResults data={results.generate_oasis} />}
              </WorkflowSection>
            </TabsContent>

            <TabsContent value="followups">
              <WorkflowSection
                action="identify_followups"
                loading={loading.identify_followups}
                result={results.identify_followups}
                onRun={() => runAnalysis("identify_followups")}
                description="Identify patients needing follow-up from notes, compliance, and risk scores"
                icon={UserCheck}
              >
                {results.identify_followups && <FollowUpIdentification data={results.identify_followups} />}
              </WorkflowSection>
            </TabsContent>

            <TabsContent value="referrals">
              <WorkflowSection
                action="suggest_referrals"
                loading={loading.suggest_referrals}
                result={results.suggest_referrals}
                onRun={() => runAnalysis("suggest_referrals")}
                description="Suggest referrals and care plan adjustments based on patient needs"
                icon={ArrowRightLeft}
              >
                {results.suggest_referrals && <ReferralSuggestions data={results.suggest_referrals} />}
              </WorkflowSection>
            </TabsContent>

            <TabsContent value="tasks">
              <WorkflowSection
                action="auto_generate_tasks"
                loading={loading.auto_generate_tasks}
                result={results.auto_generate_tasks}
                onRun={() => runAnalysis("auto_generate_tasks")}
                description="Auto-create tasks for nurses and administrators from AI-detected needs"
                icon={ListChecks}
              >
                {results.auto_generate_tasks && <AutoGeneratedTasks data={results.auto_generate_tasks} />}
              </WorkflowSection>
            </TabsContent>
          </Tabs>
        </CardContent>
      )}
    </Card>
  );
}

function WorkflowSection({ action, loading, result, onRun, description, icon: Icon, children }) {
  if (loading) {
    return (
      <div className="flex flex-col items-center py-8 text-center">
        <Loader2 className="w-6 h-6 animate-spin text-blue-500 mb-2" />
        <p className="text-xs text-slate-500">Analyzing patient data...</p>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="flex flex-col items-center py-6 text-center">
        <Icon className="w-7 h-7 text-slate-400 mb-2" />
        <p className="text-xs text-slate-500 mb-3 max-w-sm">{description}</p>
        <Button onClick={onRun} size="sm" className="bg-blue-600 hover:bg-blue-700">
          <Brain className="w-3 h-3 mr-1" /> Run Analysis
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-2">
      <div className="flex justify-end">
        <Button variant="ghost" size="sm" className="h-6 text-[10px]" onClick={onRun}>
          <RefreshCw className="w-3 h-3 mr-1" /> Re-run
        </Button>
      </div>
      {children}
    </div>
  );
}