import React from "react";
import { Badge } from "@/components/ui/badge";
import { CheckCircle2, ListChecks } from "lucide-react";

const PRIORITY_STYLE = {
  critical: "bg-red-100 text-red-700",
  high: "bg-amber-100 text-amber-700",
  medium: "bg-blue-100 text-blue-700",
  low: "bg-slate-100 text-slate-600",
};

const TYPE_EMOJI = {
  call: "📞", notify: "📢", schedule: "📅", order: "📦",
  coordinate: "🤝", document: "📝", safety: "🛡️", followup: "🔄", other: "📌",
};

export default function AutoGeneratedTasks({ data }) {
  if (!data) return null;

  return (
    <div className="space-y-3">
      {/* Summary */}
      {data.task_summary && (
        <div className="p-2.5 rounded-lg bg-gradient-to-br from-blue-100/40 to-slate-100/60 border border-blue-200/30">
          <p className="text-[11px] text-slate-700">{data.task_summary}</p>
          {data.tasks_created > 0 && (
            <div className="flex items-center gap-1 mt-1">
              <CheckCircle2 className="w-3 h-3 text-blue-600" />
              <span className="text-[10px] font-semibold text-blue-700">
                {data.tasks_created} task(s) automatically created
              </span>
            </div>
          )}
        </div>
      )}

      {/* Task List */}
      <div className="space-y-1.5">
        <p className="text-[10px] font-semibold text-slate-700 flex items-center gap-1">
          <ListChecks className="w-3 h-3" /> Generated Tasks ({data.generated_tasks?.length || 0})
        </p>
        {data.generated_tasks?.map((task, i) => (
          <div key={i} className="p-2 rounded border border-slate-200/50 bg-white/60 dark:bg-slate-900/40">
            <div className="flex items-center gap-1.5 mb-0.5">
              <span className="text-sm">{TYPE_EMOJI[task.type] || "📌"}</span>
              <Badge className={`text-[8px] px-1 py-0 ${PRIORITY_STYLE[task.priority]}`}>{task.priority}</Badge>
              <Badge variant="outline" className="text-[8px] px-1 py-0">{task.type}</Badge>
              <Badge variant="outline" className="text-[8px] px-1 py-0">
                Due: {task.due_in_days}d
              </Badge>
            </div>
            <p className="text-[11px] font-medium text-slate-800">{task.title}</p>
            <p className="text-[10px] text-slate-600 mt-0.5">{task.description}</p>
            <div className="flex gap-3 mt-0.5">
              <span className="text-[9px] text-slate-500"><strong>Assigned to:</strong> {task.target_role}</span>
            </div>
            {task.ai_reason && (
              <p className="text-[9px] text-slate-400 mt-0.5 italic">AI: {task.ai_reason}</p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}