import React from "react";
import { CheckCircle2 } from "lucide-react";
import TaskResultList from "./TaskResultList";

export default function AutoGeneratedTasks({ data }) {
  if (!data) return null;

  return (
    <div className="space-y-3">
      {data.task_summary && (
        <div className="p-2.5 rounded-lg bg-gradient-to-br from-blue-100/40 to-slate-100/60 border border-blue-200/30">
          <p className="text-[11px] text-slate-700">{data.task_summary}</p>
          {data.tasks_created > 0 && (
            <div className="flex items-center gap-1 mt-1">
              <CheckCircle2 className="w-3 h-3 text-blue-600" />
              <span className="text-[10px] font-semibold text-blue-700">
                {data.tasks_created} task(s) automatically created
              </span>
            </div>
          )}
        </div>
      )}
      <TaskResultList result={{ tasks: data.generated_tasks, tasks_created: data.tasks_created }} />
    </div>
  );
}