import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, lstatSync } from 'node:fs';

// Migration-specific baseline: last production release before external work.
// Never regenerate this value just to make an unexpected native change pass.
// An intentional native release needs separate review and device acceptance.
const BASELINE = '1ff6018cbd94d89c98dea9a95f9e48f340faf249';

// The reviewed exemptions, and the shape matters. The point of the baseline is
// that no native file changes WITHOUT a reviewer seeing it — not that none ever
// changes, which would make the hosting move unimplementable. So an intended
// change is enumerated here with its reason, and the entry is checked from both
// sides: a file here that still matches the baseline FAILS, because a stale
// exemption is a standing claim that something was reviewed when it no longer
// is. Adding a name here is the reviewed act, and the positive assertions in
// the test below it say what the new content must be.
//
// Bumping BASELINE instead would do none of this: it would make the whole
// directory agree with itself again and prove nothing about what moved.
const REVIEWED_NATIVE_CHANGES = Object.freeze({
  'ios/PennSync/WebViewController.swift':
    'D3 step two: the shell loads https://app.caremetricai.com/ instead of the Base44 subdomain, '
    + 'so a later hosting move is a DNS change rather than a second App Store release.',
  'ios/PennSync/Info.plist':
    'WKAppBoundDomains gains caremetricai.com for that origin and KEEPS both Base44 domains, '
    + 'so one binary works either side of the move while sign-in is still Base44 hosted.',
  'ios/README.md':
    'Documents the two changes above and the transitional domain set.',
  // The first entries here that are not `ios/`. The constant is named for the
  // native shell, but the assertion below only requires a path be in the pinned
  // baseline, and `public/` is pinned by the same `ls-tree`. A pinned file that
  // CHANGED belongs here rather than in the additions block above, which the
  // comment on that block says in its own words.
  //
  // All four move together and cannot be split: `build-manuals.mjs` composes the
  // Facility Admin manual as `[...userBlocks, ...adminBlocks]`, so one edit to the
  // user content rebuilds both manuals, and each is committed as HTML *and* PDF
  // because `src/pages/Help.jsx` and `src/pages/UserGuides.jsx` link the PDF.
  'public/manuals/PennSync-User-Manual.html':
    'The dashboard hospitalization risk monitor and high-risk patients widget were deleted, so the '
    + '"What\u2019s on your Dashboard" table loses both rows. Regenerated by `node scripts/build-manuals.mjs` '
    + 'from `scripts/manuals/content-user.mjs`; the word-diff is those two rows and nothing else.',
  'public/manuals/PennSync-User-Manual.pdf':
    'The PDF rendering of the HTML above, regenerated in the same run. Help links this file directly, '
    + 'so leaving it pinned would keep serving a manual that documents two widgets the app no longer has.',
  'public/manuals/PennSync-Facility-Admin-Manual.html':
    'Inherits the same two deleted rows through `[...userBlocks, ...adminBlocks]` in build-manuals.mjs, '
    + 'which is why it changed although `scripts/manuals/content-admin.mjs` never mentioned either widget.',
  'public/manuals/PennSync-Facility-Admin-Manual.pdf':
    'The PDF rendering of the Facility Admin HTML above, regenerated in the same run and linked from Help '
    + 'the same way, so it carries the same correction.',
});

// The mirror image: a file ADDED under public/ is the same kind of reviewed act.
// Each needs a reason, must be tracked, and must not be in the baseline (an
// entry that was already pinned belongs in the changes above). The packaged
// native directories cannot gain files this way, only public/ can.
const REVIEWED_PUBLIC_ADDITIONS = Object.freeze({
  'public/brand/pennsync-logo.png':
    'Hosting exit: the PennSync logo previously loaded from the Base44 storage bucket. '
    + 'Byte-identical copy so the app serves it from its own origin; the mail logo is the same file.',
  'public/brand/penn-home-health.png':
    'Hosting exit: the Penn Home Health handout image previously loaded from the Base44 '
    + 'storage bucket. Byte-identical copy served from the app origin.',
});

// execFileSync's default maxBuffer is 1 MiB; keep this in step with the same
// helper in tools-decision-register.test.mjs, where a register that crossed a
// megabyte made every base read die with ENOBUFS.
const git = (...args) =>
  execFileSync('git', args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
const paths = output => output.split('\0').filter(Boolean).sort();

// Acquiring the baseline is part of the test, not a precondition a reader is
// assumed to have met.
//
// `BASELINE` is an old commit, and a cloud container clones SHALLOW
// (`git rev-parse --is-shallow-repository` answers true in the one this was
// written in), so its objects can be absent. When they are, the `ls-tree`
// below dies with a bare `fatal: not a tree object` — which names neither this
// pin nor the clone depth — and because `test:external-integrations` is THIRD
// in the `pnpm test` chain, the nine scripts after it never run and nothing
// says so. An environment condition presented as an asset-drift failure, with
// the rest of the suite hidden behind it.
//
// The condition is measured rather than predicted, and the measurement moved:
// on 2026-10-01 a shallow container here had the baseline trees anyway and both
// probes answered PRESENT; on 2026-10-08 a fresh one answered ABSENT to both,
// and `git fetch --depth=1 origin <sha>` took about a second to fix it. So fetch
// it. Depth is a property of the checkout, never of what this test asserts.
//
// Note which probe is used: the tree WALK, which is the operation the test
// needs. `git cat-file -e <sha>^{commit}` resolves the commit object alone and
// can answer PRESENT in a tree-filtered partial clone whose walk still fails —
// a check weaker than the thing it stands in for, reporting the wrong answer in
// exactly the case it exists for.
const BASELINE_FETCH = ['fetch', '--depth=1', '--no-tags', 'origin', BASELINE];

// Which git failures mean "the objects are not in this store", MEASURED rather
// than assumed — the first version of this classifier was `status === 128` and
// was derived from one case, the absent commit. There are two shapes, and the
// second is the one a partial clone produces:
//
//   absent commit        → status 128, `fatal: not a tree object`
//   absent SUBTREE       → status 1,   `error: Could not read <oid>`
//
// So a missing `ios/` tree under a present root tree exits 1, which the old
// `=== 128` test read as NOT-absent and rethrew — escaping the fetch and the
// stand-down both, and taking the chain down exactly as before. Everything else
// (a signal from the timeout, ENOBUFS, a missing binary) still must NOT read as
// absent, or the stand-down swallows a real error: the defect
// tools-decision-register.test.mjs records against the same helper.
const isMissingObject = error => error?.status === 128
  || (error?.status === 1 && /could not read/i.test(String(error?.stderr ?? '')));

// null when the baseline's `ios`/`public` trees can be walked here; the git
// error when they cannot.
//
// `-r` is load-bearing and is the whole point: WITHOUT it this lists the root
// tree's two entries and never reads the trees underneath, so on a store whose
// root tree is present and whose `ios` tree is not it exits 0 and reports the
// baseline readable, while the assertion's own `-r` walk fails. Measured on a
// constructed store (root tree kept, `ios` tree object deleted): probe exit 0,
// assertion exit 1. A probe weaker than the operation it stands in for reports
// the wrong answer in exactly the case it exists for — which is what this
// file's own comment says about `cat-file -e`, one level further down.
function baselineUnreadable() {
  try {
    git('ls-tree', '-r', '--name-only', BASELINE, '--', 'ios', 'public');
    return null;
  } catch (error) {
    if (!isMissingObject(error)) throw error;
    return error;
  }
}

// Try once to make the baseline readable.
//
// Returns null on success, else `{ probeError, fetchError }` — the fetch's own
// error is CARRIED rather than discarded, because a `git fetch` exits 128
// whether the remote refused the object or there is no network at all (both
// measured), so its status cannot classify it and substituting the probe's
// error would report a dead network as `fatal: not a tree object`. A wrong
// reason inside a reported skip looks deliberate, which is why nothing catches
// it.
//
// A fetch killed by the timeout, or one that never ran, is NOT an unavailable
// baseline: it is this harness failing, so it rethrows instead of standing
// down. The fetch is bounded and cannot block on credentials — an offline
// container must report, not hang.
function acquireBaseline() {
  const probeError = baselineUnreadable();
  if (!probeError) return null;
  let fetchError = null;
  try {
    execFileSync('git', BASELINE_FETCH, {
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
      timeout: 120_000,
      stdio: ['ignore', 'ignore', 'pipe'],
      env: { ...process.env, GIT_TERMINAL_PROMPT: '0' },
    });
  } catch (error) {
    // Cut off (SIGTERM/SIGKILL from `timeout`) or never a git-level failure at
    // all (ENOENT on the binary, ENOBUFS): the recovery attempt itself broke.
    if (error?.signal || typeof error?.status !== 'number') throw error;
    fetchError = error;
  }
  const stillUnreadable = baselineUnreadable();
  return stillUnreadable ? { probeError: stillUnreadable, fetchError } : null;
}

test('every native and packaged public asset is byte-preserved, or enumerated with a reason', t => {
  // Fetch the pinned baseline if this checkout lacks it, and say so plainly when
  // it still cannot be read. CI clones at `fetch-depth: 0` (see ci.yml), so there
  // the objects are always present and an unreadable baseline would be a real
  // regression — fail. Elsewhere a stand-down names what was NOT checked rather
  // than reading as a pass, which is the shape tools-decision-register.test.mjs
  // settled on, and it keeps one environment condition from hiding the nine
  // `pnpm test` scripts that follow this one.
  const unreadable = acquireBaseline();
  if (unreadable) {
    const said = error => String(error?.stderr ?? '').trim() || '(nothing)';
    const shallow = (() => { try { return git('rev-parse', '--is-shallow-repository').trim(); } catch { return 'unknown'; } })();
    // Both errors, separately. The probe says what could not be read; the fetch
    // says why recovering it did not work, and those are different sentences —
    // reporting the probe's words for a dead network is how a stand-down comes
    // to carry a reason that was never measured.
    const detail = `baseline ${BASELINE} is not readable in this checkout (shallow=${shallow}). `
      + `Native/public byte preservation was NOT checked. Run: git ${BASELINE_FETCH.join(' ')}. `
      + `reading it said: ${said(unreadable.probeError)}`
      + (unreadable.fetchError ? `; fetching it said: ${said(unreadable.fetchError)}` : '; the fetch was not attempted or reported nothing');
    assert.ok(!process.env.CI,
      `CI checks out full history, so an absent baseline here is a real failure, not a shallow clone: ${detail}`);
    t.skip(detail);
    return;
  }
  const baseline = paths(git('ls-tree', '-r', '-z', '--name-only', BASELINE, '--', 'ios', 'public'));
  const current = paths(git('ls-files', '-z', '--', 'ios', 'public'));
  assert.equal(baseline.length, 25, 'Review baseline inventory changes explicitly.');
  const additions = Object.keys(REVIEWED_PUBLIC_ADDITIONS);
  for (const path of additions) {
    assert.ok(path.startsWith('public/'), `${path}: only public/ may gain files`);
    assert.ok(!baseline.includes(path), `${path} is already pinned; exempt it as a change instead`);
    assert.ok(REVIEWED_PUBLIC_ADDITIONS[path].length >= 40, `${path} needs a real reason, not a label`);
  }
  assert.deepEqual(current, [...baseline, ...additions].sort(),
    'Native/public files were added, removed or renamed.');
  // An exemption naming a file outside the pinned set proves nothing and hides
  // a typo as a pass.
  for (const path of Object.keys(REVIEWED_NATIVE_CHANGES)) {
    assert.ok(baseline.includes(path), `${path} is exempted but is not a pinned native file`);
    assert.ok(REVIEWED_NATIVE_CHANGES[path].length >= 40, `${path} needs a real reason, not a label`);
  }
  for (const path of baseline) {
    assert.equal(lstatSync(path).isFile(), true, `${path} must remain a regular file`);
    // hash-object without -w only reads the bytes. No filters or large binary
    // stdout buffers are involved, and no new Git object or artifact is written.
    const original = git('rev-parse', `${BASELINE}:${path}`).trim();
    const currentHash = git('hash-object', '--no-filters', '--', path).trim();
    if (Object.hasOwn(REVIEWED_NATIVE_CHANGES, path)) {
      assert.notEqual(currentHash, original,
        `${path} is exempted but matches the baseline — remove the stale exemption`);
      continue;
    }
    assert.equal(currentHash, original, `${path} differs from the preserved production asset`);
  }
});

test('the established app identities remain exact', () => {
  const project = readFileSync('ios/project.yml', 'utf8');
  const invitation = readFileSync('base44/functions/createUserWithTempPassword/entry.ts', 'utf8');
  assert.match(project, /PRODUCT_BUNDLE_IDENTIFIER: com\.caremetric\.ai\s/);
  // Store LISTING links. A hosting move does not touch them and must not drift
  // them, and the Apple id is what makes an upload an update rather than a new
  // app (read 2026-10-01, the public record's seller is the repository owner).
  assert.ok(invitation.includes('play.google.com/store/apps/details?id=com.caremetic.ai'));
  assert.ok(invitation.includes('6757097720'));
});

test('the invitation takes the app origin from configuration, never a literal', () => {
  // `docs/RAILWAY_GO_LIVE_PLAN_2026-09-21.md` names this file as something the
  // domain move has to edit, at lines that hold a generated SDK helper. A first
  // version of this test concluded from that that the file "holds no app origin
  // at all" and asserted the absence of two literals, which passed for the
  // wrong reason: the file DOES carry the app origin, from `APP_PUBLIC_URL`
  // (`getAppBaseUrl`), and every emailed link is built on it. So the plan's
  // intent was right and its line reference was not, and the assertion worth
  // having is about the MECHANISM: the origin stays configuration, so moving
  // the domain is one value rather than an edit here.
  const source = readFileSync('base44/functions/createUserWithTempPassword/entry.ts', 'utf8');
  assert.match(source, /Deno\.env\.get\('APP_PUBLIC_URL'\)/);
  assert.match(source, /APP_PUBLIC_URL is required for outbound app links/);
  // An origin and nothing else: no path, query, fragment or credentials, which
  // is what lets `originOf` build the manual links from it.
  assert.match(source, /APP_PUBLIC_URL must be an absolute HTTPS origin/);
  assert.match(source, /parsed\.protocol !== 'https:'/);

  // The generated shared-helper regions are excluded on purpose, and this is
  // the distinction the first version missed: `base44ClientRequest` hard-codes
  // `https://base44.app` as the SDK's BACKEND, which is not the app's public
  // origin and does not move with the domain. Outside those regions no app
  // origin may be hard-coded, or the configured one would be bypassed.
  const own = source.replace(/\/\/ <<<BEGIN SHARED HELPER[\s\S]*?\/\/ <<<END SHARED HELPER[^\n]*\n/g, '');
  assert.ok(own.includes('getAppBaseUrl'), 'the helper strip must not remove the resolver');
  assert.ok(own.length < source.length, 'the generated regions must actually be stripped');
  for (const origin of ['caremetricai.base44.app', 'app.caremetricai.com']) {
    assert.ok(!own.includes(origin), `${origin} is hard-coded where APP_PUBLIC_URL should decide`);
  }
});

test('the transitional build loads the custom domain and keeps it reachable', () => {
  const shell = readFileSync('ios/PennSync/WebViewController.swift', 'utf8');
  const plist = readFileSync('ios/PennSync/Info.plist', 'utf8');
  const appBound = [...plist.matchAll(/<key>WKAppBoundDomains<\/key>\s*<array>([\s\S]*?)<\/array>/g)];
  assert.equal(appBound.length, 1, 'exactly one WKAppBoundDomains array');
  const domains = [...appBound[0][1].matchAll(/<string>([^<]+)<\/string>/g)].map(m => m[1]);

  // The one origin the shell loads, and the only one it may load.
  const origins = [...shell.matchAll(/URL\(string: "(https:\/\/[^"]+)"\)!/g)].map(m => m[1]);
  assert.deepEqual(origins, ['https://app.caremetricai.com/']);

  // The invariant that makes the binary work at all: `appURL`'s host must be
  // covered by the app-bound list, or main-frame navigation to it is blocked
  // and the app opens to nothing. Bare entries cover subdomains, so this is a
  // suffix check at a dot boundary — never a substring one.
  const host = new URL(origins[0]).hostname;
  assert.ok(domains.some(domain => host === domain || host.endsWith(`.${domain}`)),
    `${host} is not covered by WKAppBoundDomains ${JSON.stringify(domains)}`);

  // Both Base44 domains stay while sign-in is Base44's: `/login` on the app
  // origin is a Base44-served page, and its flow can navigate the main frame to
  // a base44.app address. Removing them is a later, separate release.
  assert.deepEqual(domains, ['caremetricai.com', 'base44.app', 'base44.com']);
  // Ten is WebKit's limit; nothing here is near it, and the transitional set
  // existing at all depends on there being room for both sides.
  assert.ok(domains.length <= 10);
});

test('the shell still registers no service worker for app-bound limits to restrict', () => {
  // App-Bound Domains DO restrict service workers, which is why the plan's iOS
  // analysis turns on the frontend registering none. `src/lib/hostedPaths.spec.js`
  // asserts the frontend side; this asserts the wrapper has not grown an
  // injection path of its own, which app-bound limits also restrict.
  const shell = readFileSync('ios/PennSync/WebViewController.swift', 'utf8');
  assert.ok(shell.includes('limitsNavigationsToAppBoundDomains = true'));
  for (const api of ['WKUserScript', 'evaluateJavaScript', 'userContentController']) {
    assert.ok(!shell.includes(api), `${api} is restricted on app-bound domains`);
  }
});

// This does not inspect an uploaded IPA/AAB/APK or an App Store/Play Console
// release. It proves the listed repository assets/identities were preserved or
// deliberately changed, not that every installed app still works after a future
// backend cutover.
