// File generated bytes (a sealed signed PDF or a document rendered from a
// template) into the patient's chart exactly as createAuthorizedDocument does:
// private storage only, a metadata-only Document row, and a version-2
// DocumentTenantBinding whose binding_key is SHA-256(agency, creator, request).
// listAuthorizedDocuments / getAuthorizedDocument verify every one of these
// invariants before a chart reader sees the file, so the archive is readable
// through the ordinary chart brokers and nowhere else. The agency-level
// 'document' reservation serializes a key exactly like an upload does.
function esignChartBindingMatches(row, expected) {
  return !!esignId(row?.id) && row.binding_key === expected.bindingKey
    && !!esignId(row.document_id) && row.agency_id === expected.agencyId
    && row.patient_id === expected.patientId
    && row.created_by_user_id === expected.creator.userId
    && row.created_by_user_email_normalized === expected.creator.email
    && row.document_created_by_email_normalized === expected.creator.email
    && row.membership_id === expected.creator.membershipId
    && Number.isSafeInteger(row.membership_version) && row.membership_version >= 1
    && row.storage_mode === 'private' && isPrivateFileUri(row.file_uri)
    && row.file_type === 'application/pdf' && row.purpose === 'patient_document'
    && row.client_request_id === expected.clientRequestId && row.version === 2
    && /^[a-f0-9]{64}$/.test(String(row.content_sha256 || ''))
    && Number.isSafeInteger(row.file_size) && row.file_size > 0;
}

async function esignLoadChartBinding(entities, expected) {
  const rows = esignRows(await entities.DocumentTenantBinding.filter(
    { binding_key: expected.bindingKey }, '-created_date', ESIGN_ROW_LIMIT,
  ), 'DocumentTenantBinding.filter');
  const exact = rows.filter((row) => row?.binding_key === expected.bindingKey);
  if (exact.length > 1 || rows.length >= ESIGN_ROW_LIMIT) throw new EsignError(409, 'Chart filing identity is ambiguous');
  if (exact.length === 0) return null;
  if (!esignChartBindingMatches(exact[0], expected)) throw new EsignError(409, 'Chart filing identity conflicts with another document');
  const document = await esignExactOne(entities.Document, { id: exact[0].document_id }, 'Document', 409);
  if (document.patient_id !== expected.patientId || document.file_url != null
    || document.file_name !== exact[0].file_name) {
    throw new EsignError(409, 'Chart filing document integrity check failed');
  }
  return { binding: exact[0], document };
}

// Only a caller holding an exclusive lease over the filing (the sealing lease of
// one DocumentSignature) may clear a reservation a dead attempt left behind.
async function esignClearStaleFiling(base44, agencyId, clientRequestId, creatorUserId) {
  const entities = base44.asServiceRole.entities;
  const bindingKey = await esignSha256(agencyId + '\u0000' + creatorUserId + '\u0000' + clientRequestId);
  const key = await faxQueueCreationKey('document', bindingKey);
  const agency = await esignExactOne(entities.Agency, { id: agencyId }, 'Agency', 409);
  const token = agency.fax_workflow_reservations?.[key];
  if (typeof token !== 'string') return true;
  return releaseFaxQueueCreation(entities, { agencyId, key, token });
}

/**
 * input: { agencyId, patientId, creator: { userId, email, membershipId, membershipVersion },
 *   clientRequestId, fileName, title, render: async () => Uint8Array, extra: {} }
 * render() runs only when no filing for this key exists yet.
 */
async function esignFileChartDocument(base44, input) {
  const entities = base44.asServiceRole.entities;
  const bindingKey = await esignSha256(input.agencyId + '\u0000' + input.creator.userId + '\u0000' + input.clientRequestId);
  const expected = { ...input, bindingKey };
  const existing = await esignLoadChartBinding(entities, expected);
  if (existing) {
    await releaseRecoveredFaxQueueCreation(entities, input.agencyId, 'document', bindingKey, existing.binding).catch(() => false);
    return { ...existing, created: false };
  }
  const reservation = await reserveFaxQueueCreation(entities, input.agencyId, 'document', bindingKey);
  if (!reservation) throw new EsignError(409, 'Chart filing is already in progress; retry shortly', 'filing_in_progress');
  let createStarted = false;
  try {
    const raced = await esignLoadChartBinding(entities, expected);
    if (raced) {
      await releaseFaxQueueCreation(entities, reservation).catch(() => false);
      return { ...raced, created: false };
    }
    const bytes = await input.render();
    if (!(bytes instanceof Uint8Array) || bytes.byteLength < 8 || bytes.byteLength > 25 * 1024 * 1024) {
      throw new Error('Rendered document is invalid');
    }
    const contentSha256 = await esignSha256Bytes(bytes);
    const fileName = esignSafeFileName(input.fileName, 'Signed document');
    const upload = await base44.asServiceRole.integrations.Core.UploadPrivateFile({
      file: new File([bytes], fileName, { type: 'application/pdf' }),
    });
    const fileUri = typeof upload?.file_uri === 'string' ? upload.file_uri : '';
    if (!isPrivateFileUri(fileUri)) throw new Error('Private upload returned an invalid URI');
    const now = new Date().toISOString();
    createStarted = true;
    const document = await entities.Document.create({
      title: fileName,
      file_name: fileName,
      file_size: bytes.byteLength,
      file_type: 'application/pdf',
      category: 'other',
      patient_id: input.patientId,
      tags: ['patient_document'],
      document_date: now.slice(0, 10),
      uploaded_by: input.creator.email,
      created_by: input.creator.email,
      is_sensitive: true,
      ...(input.extra || {}),
    });
    const documentId = esignId(document?.id);
    if (!documentId) throw new Error('Document.create returned no exact id');
    const documentCreatorId = esignId(document.created_by_id);
    if (document.created_by_id != null && (!documentCreatorId
      || (documentCreatorId !== input.creator.userId && !/^service_[a-f0-9-]{36}$/.test(documentCreatorId)))) {
      throw new Error('Document.create returned invalid platform provenance');
    }
    await entities.DocumentTenantBinding.create({
      binding_key: bindingKey,
      document_id: documentId,
      agency_id: input.agencyId,
      patient_id: input.patientId,
      created_by_user_id: input.creator.userId,
      created_by_user_email_normalized: input.creator.email,
      membership_id: input.creator.membershipId,
      membership_version: input.creator.membershipVersion,
      document_created_by_email_normalized: input.creator.email,
      ...(documentCreatorId ? { document_created_by_id: documentCreatorId } : {}),
      queue_creation_reservation_token: reservation.token,
      storage_mode: 'private',
      file_uri: fileUri,
      file_name: fileName,
      file_type: 'application/pdf',
      file_size: bytes.byteLength,
      content_sha256: contentSha256,
      client_request_id: input.clientRequestId,
      purpose: 'patient_document',
      version: 2,
      created_at: now,
      last_verified_at: now,
    });
    const filed = await esignLoadChartBinding(entities, expected);
    if (!filed || filed.document.id !== documentId || filed.binding.content_sha256 !== contentSha256
      || filed.binding.file_uri !== fileUri) {
      throw new EsignError(409, 'Chart filing could not be verified');
    }
    await releaseFaxQueueCreation(entities, reservation).catch(() => false);
    return { ...filed, created: true };
  } catch (error) {
    // Once a create started, an empty read cannot prove nothing committed: keep
    // the reservation so a retry resumes the exact filing instead of duplicating it.
    if (!createStarted) await releaseFaxQueueCreation(entities, reservation).catch(() => false);
    if (error && typeof error === 'object') error.esignFilingStarted = createStarted;
    throw error;
  }
}
