import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

const AGREEMENT_VERSION = '1.0';
const AGREEMENT_ACKNOWLEDGMENTS = [
  'I understand that material generated by AI may be incomplete, inaccurate, or contain errors, and that I must not rely on it without review.',
  'I understand that I am responsible for proofreading, reviewing, and editing all AI-generated material before it is used or submitted.',
  'I understand that I am solely responsible for the accuracy, completeness, and clinical appropriateness of any material I submit, and that by submitting AI-generated material I attest that I have reviewed it and agree with its contents.',
];
const MAX_ATTESTATIONS = 50;
const NO_STORE_HEADERS = { 'Cache-Control': 'no-store' };

class PublicError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

function exactIdentifier(value) {
  if (typeof value !== 'string' || value.length > 200) return null;
  const text = value.trim();
  return text && text === value ? text : null;
}

function canonicalEmail(value) {
  if (typeof value !== 'string' || value.length > 320) return null;
  const email = value.trim().toLowerCase();
  if (!email || !email.includes('@') || /\s/.test(email)) return null;
  return email;
}

function exactIsoTimestamp(value) {
  if (typeof value !== 'string' || value.length > 40) return null;
  const date = new Date(value);
  return !Number.isNaN(date.getTime()) && date.toISOString() === value ? value : null;
}

function blockedActor(user) {
  return !user
    || user.is_active === false
    || user.disabled === true
    || user.is_service === true
    || user.is_verified === false;
}

function exactBody(body) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) return false;
  const keys = Object.keys(body).sort();
  return keys.length === 2
    && keys[0] === 'accepted'
    && keys[1] === 'agreement_version'
    && body.accepted === true
    && body.agreement_version === AGREEMENT_VERSION;
}

async function readExactActor(entities, actorId, actorEmail) {
  const rows = await entities.User.filter({ id: actorId }, undefined, 2);
  if (!Array.isArray(rows) || rows.length !== 1) {
    throw new PublicError(409, 'Authenticated user could not be reconciled');
  }
  const actor = rows[0];
  if (
    exactIdentifier(actor?.id) !== actorId
    || canonicalEmail(actor?.email) !== actorEmail
    || blockedActor(actor)
  ) {
    throw new PublicError(403, 'Authenticated user is no longer eligible');
  }
  return actor;
}

function exactAuditReadback(row, expected) {
  return exactIdentifier(row?.id) === expected.id
    && canonicalEmail(row?.user_email) === expected.user_email
    && row?.action === expected.action
    && row?.entity_type === expected.entity_type
    && row?.entity_id === expected.entity_id
    && row?.status === expected.status
    && row?.details?.agreement_version === AGREEMENT_VERSION
    && row?.details?.accepted_at === expected.details.accepted_at
    && row?.details?.severity === 'info'
    && JSON.stringify(row?.details?.acknowledgments) === JSON.stringify(AGREEMENT_ACKNOWLEDGMENTS);
}

function exactAuthorityReadback(row, actorId, actorEmail) {
  return Boolean(
    exactIdentifier(row?.id)
    && exactIdentifier(row?.user_id) === actorId
    && canonicalEmail(row?.user_email_normalized) === actorEmail
    && row?.agreement_version === AGREEMENT_VERSION
    && exactIsoTimestamp(row?.accepted_at)
    && exactIdentifier(row?.audit_event_id)
    && JSON.stringify(row?.acknowledgments) === JSON.stringify(AGREEMENT_ACKNOWLEDGMENTS)
  );
}

async function readCurrentAuthority(entities, actorId, actorEmail) {
  const rows = await entities.AIContentAgreementAttestation.filter({
    user_id: actorId,
    user_email_normalized: actorEmail,
    agreement_version: AGREEMENT_VERSION,
  }, '-created_date', MAX_ATTESTATIONS);
  if (!Array.isArray(rows) || rows.length > MAX_ATTESTATIONS) {
    throw new PublicError(409, 'Agreement authority could not be reconciled');
  }
  if (rows.some((row) => !exactAuthorityReadback(row, actorId, actorEmail))) {
    throw new PublicError(409, 'Agreement authority could not be reconciled');
  }
  return rows;
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return Response.json({ error: 'Method not allowed' }, {
      status: 405,
      headers: { ...NO_STORE_HEADERS, Allow: 'POST' },
    });
  }

  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me().catch(() => null);
    if (!user?.email) {
      return Response.json({ error: 'Unauthorized' }, { status: 401, headers: NO_STORE_HEADERS });
    }
    if (blockedActor(user)) {
      return Response.json({ error: 'Forbidden' }, { status: 403, headers: NO_STORE_HEADERS });
    }
    const actorId = exactIdentifier(user.id);
    const actorEmail = canonicalEmail(user.email);
    if (!actorId || !actorEmail) {
      return Response.json({ error: 'Forbidden' }, { status: 403, headers: NO_STORE_HEADERS });
    }

    const body = await req.json().catch(() => null);
    if (!exactBody(body)) {
      const staleVersion = body
        && typeof body === 'object'
        && !Array.isArray(body)
        && body.accepted === true
        && typeof body.agreement_version === 'string'
        && body.agreement_version !== AGREEMENT_VERSION;
      return Response.json(
        { error: staleVersion ? 'Agreement version is stale; review the current agreement' : 'Invalid request' },
        { status: staleVersion ? 409 : 400, headers: NO_STORE_HEADERS },
      );
    }

    const entities = base44.asServiceRole.entities;
    const actor = await readExactActor(entities, actorId, actorEmail);
    const existingAuthority = await readCurrentAuthority(entities, actorId, actorEmail);
    if (existingAuthority.length > 0) {
      await readExactActor(entities, actorId, actorEmail);
      return Response.json({
        success: true,
        agreement_version: AGREEMENT_VERSION,
        accepted_at: existingAuthority[0].accepted_at,
        attestation_id: existingAuthority[0].id,
      }, { headers: NO_STORE_HEADERS });
    }

    const acceptedAt = new Date().toISOString();
    const auditPayload = {
      user_email: actorEmail,
      user_name: actor.full_name || actorEmail,
      action: 'ai_content_agreement_accepted',
      entity_type: 'User',
      entity_id: actorId,
      details: {
        agreement_version: AGREEMENT_VERSION,
        accepted_at: acceptedAt,
        acknowledgments: AGREEMENT_ACKNOWLEDGMENTS,
        severity: 'info',
      },
      status: 'success',
    };

    const event = await base44.asServiceRole.entities.UserActivity.create(auditPayload);
    const eventId = exactIdentifier(event?.id);
    if (!eventId) {
      throw new PublicError(409, 'Agreement attestation could not be reconciled');
    }
    const eventRows = await base44.asServiceRole.entities.UserActivity.filter(
      { id: eventId },
      undefined,
      2,
    );
    if (
      !Array.isArray(eventRows)
      || eventRows.length !== 1
      || !exactAuditReadback(eventRows[0], { ...auditPayload, id: eventId })
    ) {
      throw new PublicError(409, 'Agreement attestation could not be reconciled');
    }

    // Recheck the protected actor after the audit append so a concurrent
    // disable cannot race into creation of gate authority.
    await readExactActor(entities, actorId, actorEmail);

    const authorityPayload = {
      user_id: actorId,
      user_email_normalized: actorEmail,
      agreement_version: AGREEMENT_VERSION,
      accepted_at: acceptedAt,
      acknowledgments: AGREEMENT_ACKNOWLEDGMENTS,
      audit_event_id: eventId,
    };
    const createdAuthority = await entities.AIContentAgreementAttestation.create(authorityPayload);
    const attestationId = exactIdentifier(createdAuthority?.id);
    if (!attestationId) {
      throw new PublicError(409, 'Agreement authority could not be reconciled');
    }
    const authorityRows = await entities.AIContentAgreementAttestation.filter({
      id: attestationId,
    }, undefined, 2);
    if (
      !Array.isArray(authorityRows)
      || authorityRows.length !== 1
      || !exactAuthorityReadback(authorityRows[0], actorId, actorEmail)
      || authorityRows[0].accepted_at !== acceptedAt
      || authorityRows[0].audit_event_id !== eventId
    ) {
      throw new PublicError(409, 'Agreement authority could not be reconciled');
    }

    // A final identity recheck keeps the response fail-closed if the account
    // was disabled while the immutable record was being appended.
    await readExactActor(entities, actorId, actorEmail);

    return Response.json({
      success: true,
      agreement_version: AGREEMENT_VERSION,
      accepted_at: acceptedAt,
      attestation_id: attestationId,
    }, { headers: NO_STORE_HEADERS });
  } catch (error) {
    if (error instanceof PublicError) {
      return Response.json({ error: error.message }, {
        status: error.status,
        headers: NO_STORE_HEADERS,
      });
    }
    // Do not emit SDK/provider details from a path that processes identity and
    // compliance state.
    console.error('acceptAiContentAgreement failed');
    return Response.json({ error: 'Internal server error' }, {
      status: 500,
      headers: NO_STORE_HEADERS,
    });
  }
});
