import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

const AGREEMENT_VERSION = '1.0';
const AGREEMENT_ACKNOWLEDGMENTS = [
  'I understand that material generated by AI may be incomplete, inaccurate, or contain errors, and that I must not rely on it without review.',
  'I understand that I am responsible for proofreading, reviewing, and editing all AI-generated material before it is used or submitted.',
  'I understand that I am solely responsible for the accuracy, completeness, and clinical appropriateness of any material I submit, and that by submitting AI-generated material I attest that I have reviewed it and agree with its contents.',
];
const MAX_ATTESTATIONS = 50;
const NO_STORE_HEADERS = { 'Cache-Control': 'no-store' };

class PublicError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

function exactIdentifier(value) {
  if (typeof value !== 'string' || value.length > 200) return null;
  const text = value.trim();
  return text && text === value ? text : null;
}

function canonicalEmail(value) {
  if (typeof value !== 'string' || value.length > 320) return null;
  const email = value.trim().toLowerCase();
  if (!email || !email.includes('@') || /\s/.test(email)) return null;
  return email;
}

function exactIsoTimestamp(value) {
  if (typeof value !== 'string' || value.length > 40) return null;
  const date = new Date(value);
  return !Number.isNaN(date.getTime()) && date.toISOString() === value ? value : null;
}

function exactEmptyBody(body) {
  return body && typeof body === 'object' && !Array.isArray(body) && Object.keys(body).length === 0;
}

function exactHistoricalVersion(value) {
  return typeof value === 'string'
    && value.length <= 40
    && /^\d+\.\d+(?:\.\d+)?$/.test(value);
}

function exactHistoricalAcknowledgments(value) {
  return Array.isArray(value)
    && value.length >= 1
    && value.length <= 10
    && value.every((item) => (
      typeof item === 'string'
      && item.length >= 1
      && item.length <= 1000
      && item.trim() === item
    ));
}

function blockedActor(user) {
  return !user
    || user.is_active === false
    || user.disabled === true
    || user.is_service === true
    || user.is_verified === false;
}

async function readExactActor(entities, actorId, actorEmail) {
  const rows = await entities.User.filter({ id: actorId }, undefined, 2);
  if (!Array.isArray(rows) || rows.length !== 1) {
    throw new PublicError(409, 'Authenticated user could not be reconciled');
  }
  const actor = rows[0];
  if (
    exactIdentifier(actor?.id) !== actorId
    || canonicalEmail(actor?.email) !== actorEmail
    || blockedActor(actor)
  ) {
    throw new PublicError(403, 'Authenticated user is no longer eligible');
  }
  return actor;
}

function structurallyValidAttestation(row, actorId, actorEmail) {
  const structurallyValid = Boolean(
    exactIdentifier(row?.id)
    && exactIdentifier(row?.user_id) === actorId
    && canonicalEmail(row?.user_email_normalized) === actorEmail
    && exactHistoricalVersion(row?.agreement_version)
    && exactIsoTimestamp(row?.accepted_at)
    && exactHistoricalAcknowledgments(row?.acknowledgments)
    && exactIdentifier(row?.audit_event_id)
  );
  if (!structurallyValid) return false;
  return row.agreement_version !== AGREEMENT_VERSION
    || JSON.stringify(row.acknowledgments) === JSON.stringify(AGREEMENT_ACKNOWLEDGMENTS);
}

function isCurrentAttestation(row) {
  return row?.agreement_version === AGREEMENT_VERSION
    && JSON.stringify(row?.acknowledgments) === JSON.stringify(AGREEMENT_ACKNOWLEDGMENTS);
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return Response.json({ error: 'Method not allowed' }, {
      status: 405,
      headers: { ...NO_STORE_HEADERS, Allow: 'POST' },
    });
  }

  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me().catch(() => null);
    if (!user?.email) {
      return Response.json({ error: 'Unauthorized' }, { status: 401, headers: NO_STORE_HEADERS });
    }
    if (blockedActor(user)) {
      return Response.json({ error: 'Forbidden' }, { status: 403, headers: NO_STORE_HEADERS });
    }
    const actorId = exactIdentifier(user.id);
    const actorEmail = canonicalEmail(user.email);
    if (!actorId || !actorEmail) {
      return Response.json({ error: 'Forbidden' }, { status: 403, headers: NO_STORE_HEADERS });
    }

    const body = await req.json().catch(() => null);
    if (!exactEmptyBody(body)) {
      return Response.json({ error: 'Invalid request' }, {
        status: 400,
        headers: NO_STORE_HEADERS,
      });
    }

    const entities = base44.asServiceRole.entities;
    await readExactActor(entities, actorId, actorEmail);

    const rows = await entities.AIContentAgreementAttestation.filter({
      user_id: actorId,
      user_email_normalized: actorEmail,
    }, '-created_date', MAX_ATTESTATIONS);

    if (!Array.isArray(rows) || rows.length > MAX_ATTESTATIONS) {
      throw new PublicError(409, 'Agreement attestations could not be reconciled');
    }
    if (rows.some((row) => !structurallyValidAttestation(row, actorId, actorEmail))) {
      throw new PublicError(409, 'Agreement attestations could not be reconciled');
    }

    // Recheck protected account state after the service-role audit read so a
    // concurrent disable cannot race into a successful gate response.
    await readExactActor(entities, actorId, actorEmail);

    return Response.json({
      accepted: rows.some(isCurrentAttestation),
      agreement_version: AGREEMENT_VERSION,
    }, { headers: NO_STORE_HEADERS });
  } catch (error) {
    if (error instanceof PublicError) {
      return Response.json({ error: error.message }, {
        status: error.status,
        headers: NO_STORE_HEADERS,
      });
    }
    console.error('getAiContentAgreementStatus failed');
    return Response.json({ error: 'Internal server error' }, {
      status: 500,
      headers: NO_STORE_HEADERS,
    });
  }
});
