import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
import { readAiPolicy } from '../../shared/aiResponsibilityPolicy.ts';

// <<<BEGIN SHARED HELPER: pennsyncProductionAppId — generated, edit base44/_shared/backendHelpers.mjs>>>
const PENNSYNC_PRODUCTION_APP_ID = '694ec16e72e01b60d22f7cbf';
// <<<END SHARED HELPER: pennsyncProductionAppId>>>
// <<<BEGIN SHARED HELPER: base44ClientRequest — generated, edit base44/_shared/backendHelpers.mjs>>>
function pinnedBase44Request(req, expectedAppId, forwardUserCredential) {
  if (typeof expectedAppId !== 'string' || expectedAppId === '') {
    throw new Error('pinned Base44 request requires an expected Base44-App-Id');
  }
  // Read the inbound headers without ever throwing on the SHAPE of req. A production
  // request is always a real Request with a Headers bag; a bare object with no usable
  // headers (a test fixture, a malformed direct call) carries no inbound header, which
  // is the absent case handled below. Only a PRESENT, different app id throws, and that
  // requires a real header an attacker would have to set — so a real Request always
  // reaches this read and the refusal is never skipped by the tolerance.
  const inbound =
    req && req.headers && typeof req.headers.get === 'function' ? req.headers : null;
  const read = (name) => (inbound ? inbound.get(name) : null);
  const received = read('Base44-App-Id');
  // Refuse only an ACTIVE mismatch: a caller presenting a DIFFERENT app id is the
  // tenant-redirect attack, and that is the case the refusal exists for. An ABSENT
  // header is not a mismatch and selects no other tenant — it only means the request
  // did not arrive through the platform, which always injects this header. We SET the
  // pinned constant below either way, so absent falls back to the correct app exactly
  // as the dropped Base44-Api-Url falls back to the default serverUrl. Throwing on
  // absent would turn every anonymous denial into a 500 instead of a clean 403.
  if (received !== null && received !== expectedAppId) {
    throw new Error(
      'Base44-App-Id mismatch: expected ' + expectedAppId + ', received ' + received
    );
  }
  const headers = new Headers();
  // Load-bearing: SET the constant (never forward the inbound value). The SDK reads
  // appId from this header and throws of its own accord when it is absent, so pinning
  // requires setting it here — dropping the inbound header alone would not suffice.
  headers.set('Base44-App-Id', expectedAppId);
  const serviceAuth = read('Base44-Service-Authorization');
  if (serviceAuth !== null) headers.set('Base44-Service-Authorization', serviceAuth);
  if (forwardUserCredential) {
    const authorization = read('Authorization');
    if (authorization !== null) headers.set('Authorization', authorization);
    const dataEnv = read('X-Data-Env');
    if (dataEnv === 'dev' || dataEnv === 'prod') headers.set('X-Data-Env', dataEnv);
  }
  // Cosmetic URL: serverUrl comes from the dropped Base44-Api-Url, not from here.
  // No method: the SDK request factory reads only headers.get(...), never the
  // method, so the request defaults to GET. An explicit POST would be inert for the
  // SDK and would read as an outbound delivery primitive to the inventory scanner
  // once this block is inlined into the fax status pollers.
  return new Request('https://base44.app', { headers });
}
function userScopedClientRequest(req, expectedAppId) {
  return pinnedBase44Request(req, expectedAppId, true);
}
function serviceRoleClientRequest(req, expectedAppId) {
  return pinnedBase44Request(req, expectedAppId, false);
}
// <<<END SHARED HELPER: base44ClientRequest>>>
const AGREEMENT_VERSION = '1.0';
const AGREEMENT_ACKNOWLEDGMENTS = [
  'I understand that material generated by AI may be incomplete, inaccurate, or contain errors, and that I must not rely on it without review.',
  'I understand that I am responsible for proofreading, reviewing, and editing all AI-generated material before it is used or submitted.',
  'I understand that I am solely responsible for the accuracy, completeness, and clinical appropriateness of any material I submit, and that by submitting AI-generated material I attest that I have reviewed it and agree with its contents.',
];
const MAX_ATTESTATIONS = 50;
const NO_STORE_HEADERS = { 'Cache-Control': 'no-store' };

class PublicError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

function exactIdentifier(value) {
  if (typeof value !== 'string' || value.length > 200) return null;
  const text = value.trim();
  return text && text === value ? text : null;
}

function canonicalEmail(value) {
  if (typeof value !== 'string' || value.length > 320) return null;
  const email = value.trim().toLowerCase();
  if (!email || !email.includes('@') || /\s/.test(email)) return null;
  return email;
}

function exactIsoTimestamp(value) {
  if (typeof value !== 'string' || value.length > 40) return null;
  const date = new Date(value);
  return !Number.isNaN(date.getTime()) && date.toISOString() === value ? value : null;
}

function exactEmptyBody(body) {
  return body && typeof body === 'object' && !Array.isArray(body) && Object.keys(body).length === 0;
}

function exactHistoricalVersion(value) {
  return typeof value === 'string'
    && value.length <= 40
    && /^\d+\.\d+(?:\.\d+)?$/.test(value);
}

function exactHistoricalAcknowledgments(value) {
  return Array.isArray(value)
    && value.length >= 1
    && value.length <= 10
    && value.every((item) => (
      typeof item === 'string'
      && item.length >= 1
      && item.length <= 1000
      && item.trim() === item
    ));
}

function blockedActor(user) {
  return !user
    || user.is_active === false
    || user.disabled === true
    || user.is_service === true
    || user.is_verified === false;
}

async function readExactActor(entities, actorId, actorEmail) {
  const rows = await entities.User.filter({ id: actorId }, undefined, 2);
  if (!Array.isArray(rows) || rows.length !== 1) {
    throw new PublicError(409, 'Authenticated user could not be reconciled');
  }
  const actor = rows[0];
  if (
    exactIdentifier(actor?.id) !== actorId
    || canonicalEmail(actor?.email) !== actorEmail
    || blockedActor(actor)
  ) {
    throw new PublicError(403, 'Authenticated user is no longer eligible');
  }
  return actor;
}

function structurallyValidAttestation(row, actorId, actorEmail) {
  const structurallyValid = Boolean(
    exactIdentifier(row?.id)
    && exactIdentifier(row?.user_id) === actorId
    && canonicalEmail(row?.user_email_normalized) === actorEmail
    && exactHistoricalVersion(row?.agreement_version)
    && exactIsoTimestamp(row?.accepted_at)
    && exactHistoricalAcknowledgments(row?.acknowledgments)
    && exactIdentifier(row?.audit_event_id)
  );
  if (!structurallyValid) return false;
  return row.agreement_version !== AGREEMENT_VERSION
    || JSON.stringify(row.acknowledgments) === JSON.stringify(AGREEMENT_ACKNOWLEDGMENTS);
}

function isCurrentAttestation(row) {
  return row?.agreement_version === AGREEMENT_VERSION
    && JSON.stringify(row?.acknowledgments) === JSON.stringify(AGREEMENT_ACKNOWLEDGMENTS);
}

export default async function(req) {
  if (req.method !== 'POST') {
    return Response.json({ error: 'Method not allowed' }, {
      status: 405,
      headers: { ...NO_STORE_HEADERS, Allow: 'POST' },
    });
  }

  try {
    const base44 = createClientFromRequest(userScopedClientRequest(req, PENNSYNC_PRODUCTION_APP_ID));
    const user = await base44.auth.me().catch(() => null);
    if (!user?.email) {
      return Response.json({ error: 'Unauthorized' }, { status: 401, headers: NO_STORE_HEADERS });
    }
    if (blockedActor(user)) {
      return Response.json({ error: 'Forbidden' }, { status: 403, headers: NO_STORE_HEADERS });
    }
    const actorId = exactIdentifier(user.id);
    const actorEmail = canonicalEmail(user.email);
    if (!actorId || !actorEmail) {
      return Response.json({ error: 'Forbidden' }, { status: 403, headers: NO_STORE_HEADERS });
    }

    const body = await req.json().catch(() => null);
    if (!exactEmptyBody(body)) {
      return Response.json({ error: 'Invalid request' }, {
        status: 400,
        headers: NO_STORE_HEADERS,
      });
    }

    const entities = base44.asServiceRole.entities;
    await readExactActor(entities, actorId, actorEmail);

    const rows = await entities.AIContentAgreementAttestation.filter({
      user_id: actorId,
      user_email_normalized: actorEmail,
    }, '-created_date', MAX_ATTESTATIONS);

    if (!Array.isArray(rows) || rows.length > MAX_ATTESTATIONS) {
      throw new PublicError(409, 'Agreement attestations could not be reconciled');
    }
    if (rows.some((row) => !structurallyValidAttestation(row, actorId, actorEmail))) {
      throw new PublicError(409, 'Agreement attestations could not be reconciled');
    }

    // Recheck protected account state after the service-role audit read so a
    // concurrent disable cannot race into a successful gate response.
    await readExactActor(entities, actorId, actorEmail);

    const policy = await readAiPolicy(entities, req.headers.get('X-Data-Env'));
    const accepted = rows.some(isCurrentAttestation);
    const bypassed = !accepted && rows.length > 0 && policy?.bypass_previously_acknowledged === true;
    return Response.json({
      accepted,
      agreement_version: AGREEMENT_VERSION,
      ...(bypassed ? { bypassed: true } : {}),
    }, { headers: NO_STORE_HEADERS });
  } catch (error) {
    if (error instanceof PublicError) {
      return Response.json({ error: error.message }, {
        status: error.status,
        headers: NO_STORE_HEADERS,
      });
    }
    console.error('getAiContentAgreementStatus failed');
    return Response.json({ error: 'Internal server error' }, {
      status: 500,
      headers: NO_STORE_HEADERS,
    });
  }
}