-- GENERATED by `node tools-read-purpose-policy.mjs --write`. Do not edit.
--
-- The authorized-document purpose policies, as SQL.
--
-- Reading a document is purpose-bound: a caller names a purpose, and the
-- purpose decides which fields are disclosed and which tenant roles may ask at
-- all. Those blocks are the authorization contract, and they are 6 purposes
-- long between them — so they are extracted from
-- `base44/functions/listAuthorizedDocuments/entry.ts` and
-- `base44/functions/getAuthorizedDocument/entry.ts`
-- rather than retyped, and re-extracted by a test on every run. A dropped
-- field name here would widen or narrow a clinical disclosure with nothing to
-- notice it.
--
-- Two vocabularies, deliberately not merged: the list capability and the
-- single-read capability each declare their own purposes, so a purpose from
-- one is not a purpose in the other and `<prefix>_known` is how each contract
-- says so.
--
-- Every function here is pure, and none of them has any authorization: they
-- answer what a policy says, never who is asking. The contracts beside them
-- are hand-written and decide that, because a capability's authorization is
-- its own.
--
-- One divergence from the originals, and it is a narrowing: platform_owner is
-- admitted by 6 of the 6 purposes and actions there and by none
-- here. D14 and D22 removed the platform tier, `caller_tenant_role` can only
-- answer one of agency_admin, manager, clinician,
-- office_staff, social_worker, spiritual_care, and emitting a branch nothing
-- can take would read like a tier that still exists. Every purpose and every
-- action still admits somebody without it; the generator refuses to render if
-- one would not.
begin;

do $$
begin
  if to_regclass('pennsync_records.document') is null
    or to_regprocedure('pennsync_records.caller_tenant_role(text)') is null then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_STORE_REQUIRED';
  end if;
end $$;

do $$
declare v_admin text := current_user;
begin
  if exists (select 1 from pg_catalog.pg_roles
    where rolname = 'pennsync_records_owner' and (rolsuper or rolbypassrls)) then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_MUST_NOT_BYPASS_RLS';
  end if;
  begin
    execute format('grant %I to current_user with set true', 'pennsync_records_owner');
  exception
    when syntax_error then execute format('grant %I to current_user', 'pennsync_records_owner');
    when others then null; -- already held, or not ours to grant; proven below
  end;
  begin
    execute format('set role %I', 'pennsync_records_owner');
    execute format('set role %I', v_admin);
  exception when others then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_NOT_ASSUMABLE';
  end;
end $$;

-- Owned by the record owner, like everything the contracts call, so a caller
-- cannot reach them and the contracts can.
set local role "pennsync_records_owner";

-- From `base44/functions/listAuthorizedDocuments/entry.ts`: 2 purposes.
create function "pennsync_records"."document_list_purpose_known"(p_purpose text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'library' then true
    when 'signature_queue' then true
    else false end
$policy$;

create function "pennsync_records"."document_list_purpose_admits"(p_purpose text, p_role text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'library' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    when 'signature_queue' then p_role in ('agency_admin', 'clinician', 'manager')
    else false end
$policy$;

-- Stable rather than immutable: a date or timestamp reaches JSON through the
-- session's DateStyle and TimeZone, so this is not constant-foldable.
create function "pennsync_records"."document_list_purpose_row"(
  p_purpose text, p "pennsync_records"."document") returns jsonb
  language sql stable set search_path = '' as $policy$
  select case p_purpose
    when 'library' then jsonb_build_object(
      'id', p."id",
      'title', p."title",
      'file_name', p."file_name",
      'file_size', p."file_size",
      'file_type', p."file_type",
      'category', p."category",
      'patient_id', p."patient_id",
      'document_date', p."document_date",
      'is_sensitive', p."is_sensitive",
      'expiration_date', p."expiration_date",
      'is_signed', p."is_signed",
      'is_locked', p."is_locked",
      'updated_date', p."updated_date")
    when 'signature_queue' then jsonb_build_object(
      'id', p."id",
      'title', p."title",
      'category', p."category",
      'patient_id', p."patient_id",
      'document_date', p."document_date",
      'expiration_date', p."expiration_date",
      'clinician_signed', p."clinician_signed",
      'clinician_signed_date', p."clinician_signed_date",
      'clinician_name', p."clinician_name",
      'patient_signed', p."patient_signed",
      'patient_signed_date', p."patient_signed_date",
      'patient_name', p."patient_name",
      'is_signed', p."is_signed",
      'is_locked', p."is_locked",
      'updated_date', p."updated_date")
    else null end
$policy$;

-- From `base44/functions/getAuthorizedDocument/entry.ts`: 4 purposes.
create function "pennsync_records"."document_exact_purpose_known"(p_purpose text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'download' then true
    when 'fax' then true
    when 'metadata' then true
    when 'signature_review' then true
    else false end
$policy$;

create function "pennsync_records"."document_exact_purpose_admits"(p_purpose text, p_role text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'download' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    when 'fax' then p_role in ('agency_admin', 'clinician', 'manager', 'office_staff', 'social_worker', 'spiritual_care')
    when 'metadata' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    when 'signature_review' then p_role in ('agency_admin', 'clinician', 'manager')
    else false end
$policy$;

-- Stable rather than immutable: a date or timestamp reaches JSON through the
-- session's DateStyle and TimeZone, so this is not constant-foldable.
create function "pennsync_records"."document_exact_purpose_row"(
  p_purpose text, p "pennsync_records"."document") returns jsonb
  language sql stable set search_path = '' as $policy$
  select case p_purpose
    when 'download' then jsonb_build_object(
      'id', p."id",
      'file_name', p."file_name",
      'file_size', p."file_size",
      'file_type', p."file_type",
      'category', p."category",
      'patient_id', p."patient_id")
    when 'fax' then jsonb_build_object(
      'id', p."id",
      'file_name', p."file_name",
      'file_size', p."file_size",
      'file_type', p."file_type",
      'category', p."category",
      'patient_id', p."patient_id")
    when 'metadata' then jsonb_build_object(
      'id', p."id",
      'title', p."title",
      'description', p."description",
      'file_name', p."file_name",
      'file_size', p."file_size",
      'file_type', p."file_type",
      'category', p."category",
      'patient_id', p."patient_id",
      'tags', p."tags",
      'document_date', p."document_date",
      'is_sensitive', p."is_sensitive",
      'expiration_date', p."expiration_date",
      'is_signed', p."is_signed",
      'is_locked', p."is_locked",
      'updated_date', p."updated_date")
    when 'signature_review' then jsonb_build_object(
      'id', p."id",
      'title', p."title",
      'category', p."category",
      'patient_id', p."patient_id",
      'document_date', p."document_date",
      'expiration_date', p."expiration_date",
      'clinician_signed', p."clinician_signed",
      'clinician_signed_date', p."clinician_signed_date",
      'clinician_name', p."clinician_name",
      'patient_signed', p."patient_signed",
      'patient_signed_date', p."patient_signed_date",
      'patient_name', p."patient_name",
      'is_signed', p."is_signed",
      'is_locked', p."is_locked",
      'updated_date', p."updated_date")
    else null end
$policy$;

reset role;

-- No caller role may ask a policy anything. The contracts are the only way in.
revoke all on function "pennsync_records"."document_list_purpose_known"(text),
  "pennsync_records"."document_list_purpose_admits"(text,text),
  "pennsync_records"."document_list_purpose_row"(text,"pennsync_records"."document"),
  "pennsync_records"."document_exact_purpose_known"(text),
  "pennsync_records"."document_exact_purpose_admits"(text,text),
  "pennsync_records"."document_exact_purpose_row"(text,"pennsync_records"."document")
  from public, anon, authenticated, service_role;

commit;
