-- GENERATED by `node tools-read-purpose-policy.mjs --write`. Do not edit.
--
-- The authorized-patient purpose policies, as SQL.
--
-- Reading a patient is purpose-bound: a caller names a purpose, and the
-- purpose decides which fields are disclosed and which tenant roles may ask at
-- all. Those blocks are the authorization contract, and they are 16 purposes
-- long between them — so they are extracted from
-- `base44/functions/listAuthorizedPatients/entry.ts` and
-- `base44/functions/getAuthorizedPatient/entry.ts`
-- rather than retyped, and re-extracted by a test on every run. A dropped
-- field name here would widen or narrow a clinical disclosure with nothing to
-- notice it.
--
-- Two vocabularies, deliberately not merged: the list capability and the
-- single-read capability each declare their own purposes, so a purpose from
-- one is not a purpose in the other and `<prefix>_known` is how each contract
-- says so.
--
-- Every function here is pure, and none of them has any authorization: they
-- answer what a policy says, never who is asking. The contracts beside them
-- are hand-written and decide that, because a capability's authorization is
-- its own.
--
-- The action policies here are the same kind of thing for a capability that
-- MUTATES a patient: 6 named workflow actions, each deciding which fields
-- it may touch and which roles may perform it. Their field sets are disjoint,
-- so a batch of actions is one write and its result does not depend on the
-- order they arrived in.
--
-- One divergence from the originals, and it is a narrowing: platform_owner is
-- admitted by 16 of the 22 purposes and actions there and by none
-- here. D14 and D22 removed the platform tier, `caller_tenant_role` can only
-- answer one of agency_admin, manager, clinician,
-- office_staff, social_worker, spiritual_care, and emitting a branch nothing
-- can take would read like a tier that still exists. Every purpose and every
-- action still admits somebody without it; the generator refuses to render if
-- one would not.
begin;

do $$
begin
  if to_regclass('pennsync_records.patient') is null
    or to_regprocedure('pennsync_records.caller_tenant_role(text)') is null then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_STORE_REQUIRED';
  end if;
end $$;

do $$
declare v_admin text := current_user;
begin
  if exists (select 1 from pg_catalog.pg_roles
    where rolname = 'pennsync_records_owner' and (rolsuper or rolbypassrls)) then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_MUST_NOT_BYPASS_RLS';
  end if;
  begin
    execute format('grant %I to current_user with set true', 'pennsync_records_owner');
  exception
    when syntax_error then execute format('grant %I to current_user', 'pennsync_records_owner');
    when others then null; -- already held, or not ours to grant; proven below
  end;
  begin
    execute format('set role %I', 'pennsync_records_owner');
    execute format('set role %I', v_admin);
  exception when others then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_NOT_ASSUMABLE';
  end;
end $$;

-- Owned by the record owner, like everything the contracts call, so a caller
-- cannot reach them and the contracts can.
set local role "pennsync_records_owner";

-- From `base44/functions/listAuthorizedPatients/entry.ts`: 8 purposes.
create function "pennsync_records"."patient_list_purpose_known"(p_purpose text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'contact' then true
    when 'data_quality' then true
    when 'deduplication' then true
    when 'education_delivery' then true
    when 'identity_match' then true
    when 'patient_management' then true
    when 'risk_analysis' then true
    when 'roster' then true
    else false end
$policy$;

create function "pennsync_records"."patient_list_purpose_admits"(p_purpose text, p_role text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'contact' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'data_quality' then p_role in ('agency_admin', 'manager')
    when 'deduplication' then p_role in ('agency_admin', 'clinician', 'manager', 'office_staff')
    when 'education_delivery' then p_role in ('agency_admin', 'clinician', 'manager', 'office_staff', 'social_worker', 'spiritual_care')
    when 'identity_match' then p_role in ('agency_admin', 'manager')
    when 'patient_management' then p_role in ('agency_admin', 'clinician', 'manager', 'office_staff', 'social_worker', 'spiritual_care')
    when 'risk_analysis' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'roster' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    else false end
$policy$;

create function "pennsync_records"."patient_list_purpose_page_size"(p_purpose text) returns integer
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'contact' then 25
    when 'data_quality' then 50
    when 'deduplication' then 25
    when 'education_delivery' then 50
    when 'identity_match' then 25
    when 'patient_management' then 50
    when 'risk_analysis' then 50
    when 'roster' then 50
    else null end
$policy$;

-- Stable rather than immutable: a date or timestamp reaches JSON through the
-- session's DateStyle and TimeZone, so this is not constant-foldable.
create function "pennsync_records"."patient_list_purpose_row"(
  p_purpose text, p "pennsync_records"."patient") returns jsonb
  language sql stable set search_path = '' as $policy$
  select case p_purpose
    when 'contact' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'phone', p."phone",
      'email', p."email",
      'emergency_contact_name', p."emergency_contact_name",
      'emergency_contact_phone', p."emergency_contact_phone",
      'emergency_contact_relationship', p."emergency_contact_relationship",
      'physician_name', p."physician_name",
      'physician_phone', p."physician_phone",
      'physician_email', p."physician_email",
      'caregiver_name', p."caregiver_name",
      'caregiver_email', p."caregiver_email",
      'caregiver_phone', p."caregiver_phone")
    when 'data_quality' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'status', p."status",
      'phone', p."phone",
      'emergency_contact_name', p."emergency_contact_name",
      'emergency_contact_phone', p."emergency_contact_phone",
      'physician_name', p."physician_name",
      'updated_date', p."updated_date")
    when 'deduplication' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'date_of_birth', p."date_of_birth",
      'medical_record_number', p."medical_record_number",
      'address', p."address",
      'phone', p."phone",
      'email', p."email",
      'emergency_contact_phone', p."emergency_contact_phone",
      'caregiver_email', p."caregiver_email",
      'caregiver_phone', p."caregiver_phone",
      'physician_email', p."physician_email",
      'status', p."status",
      'created_date', p."created_date",
      'updated_date', p."updated_date")
    when 'education_delivery' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'medical_record_number', p."medical_record_number",
      'status', p."status",
      'care_type', p."care_type",
      'primary_diagnosis', p."primary_diagnosis",
      'email', p."email",
      'updated_date', p."updated_date")
    when 'identity_match' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'date_of_birth', p."date_of_birth",
      'medical_record_number', p."medical_record_number",
      'phone', p."phone",
      'address', p."address")
    when 'patient_management' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'date_of_birth', p."date_of_birth",
      'medical_record_number', p."medical_record_number",
      'address', p."address",
      'phone', p."phone",
      'email', p."email",
      'status', p."status",
      'care_type', p."care_type",
      'admission_date', p."admission_date",
      'primary_diagnosis', p."primary_diagnosis",
      'secondary_diagnoses', p."secondary_diagnoses",
      'allergies', p."allergies",
      'created_date', p."created_date",
      'updated_date', p."updated_date")
    when 'risk_analysis' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'date_of_birth', p."date_of_birth",
      'status', p."status",
      'care_type', p."care_type",
      'admission_date', p."admission_date",
      'primary_diagnosis', p."primary_diagnosis",
      'secondary_diagnoses', p."secondary_diagnoses",
      'past_hospitalizations', p."past_hospitalizations",
      'updated_date', p."updated_date")
    when 'roster' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'medical_record_number', p."medical_record_number",
      'status', p."status",
      'care_type', p."care_type",
      'admission_date', p."admission_date",
      'primary_diagnosis', p."primary_diagnosis",
      'updated_date', p."updated_date")
    else null end
$policy$;

-- From `base44/functions/getAuthorizedPatient/entry.ts`: 8 purposes.
create function "pennsync_records"."patient_exact_purpose_known"(p_purpose text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'alert_analysis' then true
    when 'display' then true
    when 'education_context' then true
    when 'health_history_write_base' then true
    when 'oasis_analysis_context' then true
    when 'selector' then true
    when 'smart_note_context' then true
    when 'visit_summary' then true
    else false end
$policy$;

create function "pennsync_records"."patient_exact_purpose_admits"(p_purpose text, p_role text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'alert_analysis' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'display' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    when 'education_context' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    when 'health_history_write_base' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'oasis_analysis_context' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'selector' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    when 'smart_note_context' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'visit_summary' then p_role in ('agency_admin', 'clinician', 'manager', 'social_worker', 'spiritual_care')
    else false end
$policy$;

-- Stable rather than immutable: a date or timestamp reaches JSON through the
-- session's DateStyle and TimeZone, so this is not constant-foldable.
create function "pennsync_records"."patient_exact_purpose_row"(
  p_purpose text, p "pennsync_records"."patient") returns jsonb
  language sql stable set search_path = '' as $policy$
  select case p_purpose
    when 'alert_analysis' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'primary_diagnosis', p."primary_diagnosis",
      'secondary_diagnoses', p."secondary_diagnoses",
      'care_type', p."care_type",
      'status', p."status",
      'allergies', p."allergies")
    when 'display' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name")
    when 'education_context' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'primary_diagnosis', p."primary_diagnosis",
      'physician_name', p."physician_name",
      'allergies', p."allergies")
    when 'health_history_write_base' then jsonb_build_object(
      'id', p."id",
      'past_medical_history', p."past_medical_history",
      'past_hospitalizations', p."past_hospitalizations",
      'updated_date', p."updated_date")
    when 'oasis_analysis_context' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'date_of_birth', p."date_of_birth",
      'admission_date', p."admission_date",
      'admission_source', p."admission_source",
      'primary_diagnosis', p."primary_diagnosis",
      'secondary_diagnoses', p."secondary_diagnoses",
      'allergies', p."allergies",
      'current_medications', p."current_medications",
      'functional_status', p."functional_status",
      'baseline_vitals', p."baseline_vitals",
      'social_history', p."social_history",
      'advance_directives', p."advance_directives",
      'past_hospitalizations', p."past_hospitalizations",
      'updated_date', p."updated_date")
    when 'selector' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'medical_record_number', p."medical_record_number",
      'status', p."status",
      'care_type', p."care_type",
      'primary_diagnosis', p."primary_diagnosis",
      'updated_date', p."updated_date")
    when 'smart_note_context' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'date_of_birth', p."date_of_birth",
      'medical_record_number', p."medical_record_number",
      'status', p."status",
      'care_type', p."care_type",
      'primary_diagnosis', p."primary_diagnosis",
      'secondary_diagnoses', p."secondary_diagnoses",
      'chronic_conditions', p."chronic_conditions",
      'past_medical_history', p."past_medical_history",
      'current_medications', p."current_medications",
      'allergies', p."allergies",
      'functional_status', p."functional_status",
      'wounds', p."wounds",
      'enhanced_notes_history', p."enhanced_notes_history",
      'clinical_notes', p."clinical_notes",
      'updated_date', p."updated_date")
    when 'visit_summary' then jsonb_build_object(
      'id', p."id",
      'first_name', p."first_name",
      'middle_name', p."middle_name",
      'last_name', p."last_name",
      'date_of_birth', p."date_of_birth",
      'primary_diagnosis', p."primary_diagnosis")
    else null end
$policy$;

-- The fields a client may supply to `createAuthorizedPatient`
-- (43 of the 46 its `CLIENT_PATIENT_FIELDS` declares; the other
-- 3 are the contract's to decide, and it refuses a payload naming one).
create function "pennsync_records"."patient_create_writable"(p_field text) returns boolean
  language sql immutable set search_path = '' as $write$
  select p_field in ('first_name', 'middle_name', 'last_name', 'date_of_birth', 'medical_record_number', 'address', 'phone', 'email', 'payor', 'emergency_contact_name', 'emergency_contact_phone', 'emergency_contact_relationship', 'physician_name', 'physician_phone', 'physician_email', 'caregiver_name', 'caregiver_email', 'caregiver_phone', 'primary_diagnosis', 'secondary_diagnoses', 'chronic_conditions', 'past_surgeries', 'family_medical_history', 'social_determinants', 'allergies', 'current_medications', 'past_medical_history', 'past_hospitalizations', 'baseline_vitals', 'functional_status', 'social_history', 'mental_health', 'pain_management', 'wounds', 'advance_directives', 'insurance_primary', 'insurance_secondary', 'admission_date', 'admission_source', 'care_type', 'validation_overrides', 'clinical_notes', 'goals_of_care')
$write$;

create function "pennsync_records"."patient_create_reserved"(p_field text) returns boolean
  language sql immutable set search_path = '' as $write$
  select p_field in ('agency_id', 'client_request_id', 'status')
$write$;

-- The workflow actions `updateAuthorizedPatient` accepts
-- (6 of them over 29 fields, from its own `ACTION_FIELD_NAMES`
-- and `ACTION_ROLE_NAMES`). The field sets are disjoint and the generator
-- refuses to render if they stop being, because the original merges a batch
-- of actions into ONE write and two actions assigning one field would make
-- the answer depend on their order.
create function "pennsync_records"."patient_action_known"(p_action text) returns boolean
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'edit_demographics' then true
    when 'edit_clinical_profile' then true
    when 'edit_care_episode' then true
    when 'edit_insurance' then true
    when 'set_primary_diagnosis' then true
    when 'change_status' then true
    else false end
$action$;

create function "pennsync_records"."patient_action_admits"(p_action text, p_role text) returns boolean
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'edit_demographics' then p_role in ('agency_admin', 'clinician', 'manager', 'office_staff')
    when 'edit_clinical_profile' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'edit_care_episode' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'edit_insurance' then p_role in ('agency_admin', 'manager', 'office_staff')
    when 'set_primary_diagnosis' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'change_status' then p_role in ('agency_admin', 'clinician', 'manager')
    else false end
$action$;

create function "pennsync_records"."patient_action_writes"(p_action text, p_field text) returns boolean
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'edit_demographics' then p_field in ('first_name', 'middle_name', 'last_name', 'date_of_birth', 'medical_record_number', 'address', 'phone', 'email', 'emergency_contact_name', 'emergency_contact_phone', 'emergency_contact_relationship', 'physician_name', 'physician_phone', 'physician_email', 'caregiver_name', 'caregiver_email', 'caregiver_phone')
    when 'edit_clinical_profile' then p_field in ('secondary_diagnoses', 'allergies', 'past_medical_history', 'goals_of_care')
    when 'edit_care_episode' then p_field in ('admission_date', 'admission_source', 'care_type')
    when 'edit_insurance' then p_field in ('payor')
    when 'set_primary_diagnosis' then p_field in ('primary_diagnosis')
    when 'change_status' then p_field in ('status', 'discharge_date', 'discharge_disposition')
    else false end
$action$;

-- The original's `ACTION_CANONICAL_ORDER`: the order the declaration is
-- written in, which it sorts a submitted batch into so that the answer does
-- not depend on the order a caller happened to send.
create function "pennsync_records"."patient_action_rank"(p_action text) returns integer
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'edit_demographics' then 1
    when 'edit_clinical_profile' then 2
    when 'edit_care_episode' then 3
    when 'edit_insurance' then 4
    when 'set_primary_diagnosis' then 5
    when 'change_status' then 6
    else null end
$action$;

reset role;

-- No caller role may ask a policy anything. The contracts are the only way in.
revoke all on function "pennsync_records"."patient_list_purpose_known"(text),
  "pennsync_records"."patient_list_purpose_admits"(text,text),
  "pennsync_records"."patient_list_purpose_page_size"(text),
  "pennsync_records"."patient_list_purpose_row"(text,"pennsync_records"."patient"),
  "pennsync_records"."patient_exact_purpose_known"(text),
  "pennsync_records"."patient_exact_purpose_admits"(text,text),
  "pennsync_records"."patient_exact_purpose_row"(text,"pennsync_records"."patient"),
  "pennsync_records"."patient_create_writable"(text),
  "pennsync_records"."patient_create_reserved"(text),
  "pennsync_records"."patient_action_known"(text),
  "pennsync_records"."patient_action_admits"(text,text),
  "pennsync_records"."patient_action_writes"(text,text),
  "pennsync_records"."patient_action_rank"(text)
  from public, anon, authenticated, service_role;

commit;
