-- The tenant-scoped broker family: 5 operations over 3 brokered entities.
--
-- GENERATED by `node tools-record-brokers.mjs --write`. Do not edit by hand: a
-- test regenerates this file and fails if it differs. Change the dispositions,
-- the tenant decisions or the generator instead.
--
-- The record store grants no caller role a table, a helper, or even USAGE on
-- its schema, because an RLS policy is evaluated with the privileges of the
-- role running the query: a caller holding the table would also need the
-- helpers that decide who it is. This migration is the only bridge across that,
-- and it grants a caller role USAGE on the schema and EXECUTE on these five
-- functions — nothing else, and never a table.
begin;

-- The store this brokers has to exist, and the owner has to be one row level
-- security still binds. A pre-existing owner carrying BYPASSRLS would make
-- every broker below a way around all 596 policies rather than through them.
do $$
begin
  if to_regnamespace('pennsync_records') is null then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_STORE_REQUIRED';
  end if;
end $$;

do $$
declare v_admin text := current_user;
begin
  if not exists (select 1 from pg_catalog.pg_roles where rolname = 'pennsync_records_owner') then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_REQUIRED';
  end if;
  if exists (select 1 from pg_catalog.pg_roles
    where rolname = 'pennsync_records_owner' and (rolsuper or rolbypassrls)) then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_MUST_NOT_BYPASS_RLS';
  end if;
  -- Same PostgreSQL 16 CREATEROLE problem the store's own migration hit: a role
  -- you created is not a role you may act as. Ask for SET explicitly, then prove
  -- it by doing it, because the privilege names differ across versions.
  begin
    execute format('grant %I to current_user with set true', 'pennsync_records_owner');
  exception
    when syntax_error then execute format('grant %I to current_user', 'pennsync_records_owner');
    when others then null; -- already held, or not ours to grant; proven below
  end;
  begin
    execute format('set role %I', 'pennsync_records_owner');
    execute format('set role %I', v_admin);
  exception when others then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_NOT_ASSUMABLE';
  end;
end $$;

-- Everything below belongs to the owner, so SECURITY DEFINER puts a broker
-- inside the owner's privileges — which `force row level security` binds —
-- rather than outside them.
set local role "pennsync_records_owner";

-- The allowlist. An entity absent from it is not reachable through this
-- family at all, whatever its table looks like: 3 of the store's tables, every
-- one of them checked against D2's ceiling by `check:tenant-decisions` before
-- this file could be generated.
create function "pennsync_records"."brokered"(p_entity text)
  returns table(tbl text, mode text, subject text)
  language sql immutable set search_path = '' as $broker$
  select t.tbl, t.mode, t.subject from (values
    ('Announcement'::text, 'announcement'::text, 'readonly'::text, null::text),
    ('FacilityDocumentationRule', 'facility_documentation_rule', 'readonly', null),
    ('RegulatoryUpdate', 'regulatory_update', 'readonly', null)
  ) as t(entity, tbl, mode, subject)
  where t.entity = p_entity
$broker$;

-- The gate every operation runs first: a named agency the caller actually
-- holds, and an entity this family serves. Deliberately not granted to any
-- caller role, so it cannot be called on its own to probe either answer.
create function "pennsync_records"."broker_scope"(p_agency text, p_entity text)
  returns table(tbl text, mode text, subject text)
  language plpgsql stable set search_path = '' as $broker$
declare v_found record;
begin
  if p_agency is null or p_agency = '' then
    raise exception using errcode='22023', message='PENNSYNC_BROKER_AGENCY_REQUIRED';
  end if;
  -- Against the membership roster, never against the request.
  if not exists (select 1 from "pennsync_records"."caller_agencies"() as held(agency) where held.agency = p_agency) then
    raise exception using errcode='42501', message='PENNSYNC_BROKER_AGENCY_NOT_HELD';
  end if;
  select b.tbl, b.mode, b.subject into v_found from "pennsync_records"."brokered"(p_entity) b;
  if v_found.tbl is null then
    raise exception using errcode='42501', message='PENNSYNC_BROKER_ENTITY_NOT_BROKERED';
  end if;
  return query select v_found.tbl, v_found.mode, v_found.subject;
end $broker$;

-- What the broker sets and a payload may not.
create function "pennsync_records"."broker_reserved"(p_mode text, p_subject text)
  returns text[] language sql immutable set search_path = '' as $broker$
  select case
    when p_mode = any(array['tenant', 'readonly']) then array['source_app_id', 'id', 'created_date', 'updated_date', 'created_by', 'agency_id']
    when p_mode = 'self' then array['source_app_id', 'id', 'created_date', 'updated_date', 'created_by'] || p_subject
    else array['source_app_id', 'id', 'created_date', 'updated_date', 'created_by']
  end
$broker$;

-- A payload key that is stamped, or that is not a column at all, is REFUSED
-- rather than dropped. Dropping it leaves a caller believing it wrote a field
-- it did not, which is the same defect whether the field was tenancy or a typo.
create function "pennsync_records"."broker_check_payload"(p_table text, p_payload jsonb, p_reserved text[])
  returns void language plpgsql stable set search_path = '' as $broker$
declare v_key text; v_columns text[];
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception using errcode='22023', message='PENNSYNC_BROKER_RECORD_REQUIRED';
  end if;
  select array_agg(a.attname::text) into v_columns
  from pg_catalog.pg_attribute a
  where a.attrelid = format('%I.%I', 'pennsync_records', p_table)::regclass
    and a.attnum > 0 and not a.attisdropped;
  for v_key in select k from jsonb_object_keys(p_payload) k loop
    if v_key = any(p_reserved) then
      raise exception using errcode='42501', message='PENNSYNC_BROKER_COLUMN_NOT_WRITABLE', detail = v_key;
    end if;
    if not (v_key = any(v_columns)) then
      raise exception using errcode='42703', message='PENNSYNC_BROKER_COLUMN_UNKNOWN', detail = v_key;
    end if;
  end loop;
end $broker$;

-- Keyset pagination on the primary key, so a page is stable while rows are
-- being written and no offset is scanned to reach it.
create function "pennsync_records"."entity_list"(p_agency text, p_entity text,
  p_limit integer default 50, p_after text default null)
  returns setof jsonb language plpgsql stable security definer set search_path = '' as $broker$
declare v_scope record; v_limit integer;
begin
  select * into v_scope from "pennsync_records"."broker_scope"(p_agency, p_entity);
  v_limit := least(greatest(coalesce(p_limit, 50), 1), 5000);
  -- The only narrowing this family does: one agency out of the several a caller
  -- may hold. Everything else about who sees what is left to the policies.
  if v_scope.mode = any(array['tenant', 'readonly']) then
    return query execute format(
      'select to_jsonb(t) from %I.%I t where t.%I = $2 and ($1 is null or t.%I > $1) order by t.%I limit %L::integer',
      'pennsync_records', v_scope.tbl, 'agency_id', 'id', 'id', v_limit)
      using p_after, p_agency;
  else
    return query execute format(
      'select to_jsonb(t) from %I.%I t where ($1 is null or t.%I > $1) order by t.%I limit %L::integer',
      'pennsync_records', v_scope.tbl, 'id', 'id', v_limit)
      using p_after;
  end if;
end $broker$;

-- Absent and invisible answer the same way on purpose: telling them apart
-- reports whether an id exists in another agency.
create function "pennsync_records"."entity_get"(p_agency text, p_entity text, p_id text)
  returns jsonb language plpgsql stable security definer set search_path = '' as $broker$
declare v_scope record; v_row jsonb;
begin
  select * into v_scope from "pennsync_records"."broker_scope"(p_agency, p_entity);
  if p_id is null or p_id = '' then
    raise exception using errcode='22023', message='PENNSYNC_BROKER_ID_REQUIRED';
  end if;
  if v_scope.mode = any(array['tenant', 'readonly']) then
    execute format('select to_jsonb(t) from %I.%I t where t.%I = $1 and t.%I = $2',
      'pennsync_records', v_scope.tbl, 'id', 'agency_id') into v_row using p_id, p_agency;
  else
    execute format('select to_jsonb(t) from %I.%I t where t.%I = $1',
      'pennsync_records', v_scope.tbl, 'id') into v_row using p_id;
  end if;
  return v_row;
end $broker$;

-- The id is generated here rather than accepted. A caller choosing one could
-- collide with a row it is allowed to see inside its own agency, and an id is
-- not a field anyone needs to choose.
create function "pennsync_records"."entity_insert"(p_agency text, p_entity text, p_record jsonb)
  returns jsonb language plpgsql volatile security definer set search_path = '' as $broker$
declare v_scope record; v_row jsonb; v_stamped jsonb; v_now timestamptz := now();
begin
  select * into v_scope from "pennsync_records"."broker_scope"(p_agency, p_entity);
  if v_scope.mode = any(array['global', 'readonly']) then
    raise exception using errcode='42501', message='PENNSYNC_BROKER_ENTITY_READ_ONLY';
  end if;
  perform "pennsync_records"."broker_check_payload"(v_scope.tbl, p_record,
    "pennsync_records"."broker_reserved"(v_scope.mode, v_scope.subject));
  v_stamped := jsonb_build_object(
    'source_app_id', "pennsync_records"."deployment_app"(),
    'id', replace(gen_random_uuid()::text, '-', ''),
    'created_date', to_jsonb(v_now),
    'updated_date', to_jsonb(v_now),
    'created_by', to_jsonb("pennsync_records"."caller_email"()));
  if v_scope.mode = any(array['tenant', 'readonly']) then
    v_stamped := v_stamped || jsonb_build_object('agency_id', p_agency);
  elsif v_scope.mode = 'self' then
    v_stamped := v_stamped || jsonb_build_object(v_scope.subject, case v_scope.subject
      when 'user_id' then "pennsync_records"."caller_user_id"()
      when 'user_email' then "pennsync_records"."caller_email"()
    end);
  end if;
  execute format('insert into %I.%I as t select r.* from jsonb_populate_record(null::%I.%I, $1) r returning to_jsonb(t)',
    'pennsync_records', v_scope.tbl, 'pennsync_records', v_scope.tbl) into v_row using (p_record || v_stamped);
  return v_row;
end $broker$;

-- A patch, not a replacement: absent keys keep their stored value, and a key
-- holding JSON null clears its column, which is what an explicit null means.
create function "pennsync_records"."entity_update"(p_agency text, p_entity text, p_id text, p_patch jsonb)
  returns jsonb language plpgsql volatile security definer set search_path = '' as $broker$
declare v_scope record; v_row jsonb; v_key text; v_sets text[] := array[]::text[]; v_sql text;
begin
  select * into v_scope from "pennsync_records"."broker_scope"(p_agency, p_entity);
  if v_scope.mode = any(array['global', 'readonly']) then
    raise exception using errcode='42501', message='PENNSYNC_BROKER_ENTITY_READ_ONLY';
  end if;
  if p_id is null or p_id = '' then
    raise exception using errcode='22023', message='PENNSYNC_BROKER_ID_REQUIRED';
  end if;
  perform "pennsync_records"."broker_check_payload"(v_scope.tbl, p_patch,
    "pennsync_records"."broker_reserved"(v_scope.mode, v_scope.subject));
  for v_key in select k from jsonb_object_keys(p_patch) k loop
    v_sets := v_sets || format('%I = (jsonb_populate_record(null::%I.%I, $1)).%I',
      v_key, 'pennsync_records', v_scope.tbl, v_key);
  end loop;
  v_sets := v_sets || format('%I = now()', 'updated_date');
  v_sql := format('update %I.%I as t set %s where t.%I = $2',
    'pennsync_records', v_scope.tbl, array_to_string(v_sets, ', '), 'id');
  if v_scope.mode = any(array['tenant', 'readonly']) then
    v_sql := v_sql || format(' and t.%I = $3', 'agency_id');
    execute v_sql || ' returning to_jsonb(t)' into v_row using p_patch, p_id, p_agency;
  else
    execute v_sql || ' returning to_jsonb(t)' into v_row using p_patch, p_id;
  end if;
  return v_row;
end $broker$;

-- False for a row that was not there and for one that was not this caller's
-- to remove, for the same reason `entity_get` answers null to both.
create function "pennsync_records"."entity_delete"(p_agency text, p_entity text, p_id text)
  returns boolean language plpgsql volatile security definer set search_path = '' as $broker$
declare v_scope record; v_removed boolean;
begin
  select * into v_scope from "pennsync_records"."broker_scope"(p_agency, p_entity);
  if v_scope.mode = any(array['global', 'readonly']) then
    raise exception using errcode='42501', message='PENNSYNC_BROKER_ENTITY_READ_ONLY';
  end if;
  if p_id is null or p_id = '' then
    raise exception using errcode='22023', message='PENNSYNC_BROKER_ID_REQUIRED';
  end if;
  if v_scope.mode = any(array['tenant', 'readonly']) then
    execute format('with gone as (delete from %I.%I as t where t.%I = $1 and t.%I = $2 returning 1) select count(*) > 0 from gone',
      'pennsync_records', v_scope.tbl, 'id', 'agency_id') into v_removed using p_id, p_agency;
  else
    execute format('with gone as (delete from %I.%I as t where t.%I = $1 returning 1) select count(*) > 0 from gone',
      'pennsync_records', v_scope.tbl, 'id') into v_removed using p_id;
  end if;
  return v_removed;
end $broker$;

reset role;

-- EXECUTE on a function is granted to PUBLIC by default, so every one of
-- these has to be revoked before anything is granted back. The four internals
-- are never granted: only the five operations are reachable.
revoke all on function "pennsync_records"."brokered"(text), "pennsync_records"."broker_scope"(text,text), "pennsync_records"."broker_reserved"(text,text), "pennsync_records"."broker_check_payload"(text,jsonb,text[]), "pennsync_records"."entity_list"(text,text,integer,text), "pennsync_records"."entity_get"(text,text,text), "pennsync_records"."entity_insert"(text,text,jsonb), "pennsync_records"."entity_update"(text,text,text,jsonb), "pennsync_records"."entity_delete"(text,text,text) from public, anon, authenticated, service_role;

grant usage on schema "pennsync_records" to authenticated;

grant execute on function "pennsync_records"."entity_list"(text,text,integer,text), "pennsync_records"."entity_get"(text,text,text), "pennsync_records"."entity_insert"(text,text,jsonb), "pennsync_records"."entity_update"(text,text,text,jsonb), "pennsync_records"."entity_delete"(text,text,text) to authenticated;

-- SECURITY INVOKER wrappers in an exposed schema, so PostgREST can reach the
-- family without the project exposing `pennsync_records` itself. They run as the
-- caller and add nothing: the authority store's own RPC surface has the same
-- shape, for the same reason.
create function "public"."pennsync_records_list"(p_agency text, p_entity text, p_limit integer default 50, p_after text default null) returns jsonb
  language sql security invoker set search_path = '' as $broker$
  select coalesce(jsonb_agg(page.row order by page.row->>'id'), '[]'::jsonb)
  from (select * from "pennsync_records"."entity_list"(p_agency, p_entity, p_limit, p_after) as row) page
$broker$;

create function "public"."pennsync_records_get"(p_agency text, p_entity text, p_id text) returns jsonb
  language sql security invoker set search_path = '' as $broker$
  select "pennsync_records"."entity_get"(p_agency, p_entity, p_id)
$broker$;

create function "public"."pennsync_records_insert"(p_agency text, p_entity text, p_record jsonb) returns jsonb
  language sql security invoker set search_path = '' as $broker$
  select "pennsync_records"."entity_insert"(p_agency, p_entity, p_record)
$broker$;

create function "public"."pennsync_records_update"(p_agency text, p_entity text, p_id text, p_patch jsonb) returns jsonb
  language sql security invoker set search_path = '' as $broker$
  select "pennsync_records"."entity_update"(p_agency, p_entity, p_id, p_patch)
$broker$;

create function "public"."pennsync_records_delete"(p_agency text, p_entity text, p_id text) returns boolean
  language sql security invoker set search_path = '' as $broker$
  select "pennsync_records"."entity_delete"(p_agency, p_entity, p_id)
$broker$;

revoke all on function "public"."pennsync_records_list"(text,text,integer,text), "public"."pennsync_records_get"(text,text,text), "public"."pennsync_records_insert"(text,text,jsonb), "public"."pennsync_records_update"(text,text,text,jsonb), "public"."pennsync_records_delete"(text,text,text) from public, anon, authenticated, service_role;

grant execute on function "public"."pennsync_records_list"(text,text,integer,text), "public"."pennsync_records_get"(text,text,text), "public"."pennsync_records_insert"(text,text,jsonb), "public"."pennsync_records_update"(text,text,text,jsonb), "public"."pennsync_records_delete"(text,text,text) to authenticated;

-- Still no grant to anon or service_role anywhere above, and still no grant on
-- any table to anyone. A service credential cannot read past the caller it is
-- acting for, because there is nothing for it to read past the caller with.
commit;
