-- The entity schemas' column defaults, for a store that already exists (D88).
--
-- `planEntity` never read a property's `default`, so the generated store
-- emitted none of the 425 the carried schemas declare. That is not cosmetic:
-- where a contract's INSERT omits such a column the row stored a null, while
-- the Base44 original stored the schema's value. Sixteen columns across six
-- contracts are in that state -- among them `incident.state_reportable`,
-- whose STORED value D44's resolve gate reads, and `physician.referral_count`,
-- which a null makes increment to null.
--
-- Sixteen, and not the thirty-one first measured: an INSERT column list is NOT
-- what the row holds at commit. The timesheet submit inserts a skeleton of
-- seven columns and then UPDATEs `status` and all ten payroll numerics in the
-- same transaction, so the row never exists with a null in any of them. The
-- instrument read insert lists and called an omitted column a divergence.
--
-- DERIVED, never typed: `node tools-pennsync-record-catchup.mjs --write` reads
-- every emitted `default` out of the generated migration. Four hundred and
-- twenty-five retyped literals is exactly the transcription D12 settled
-- against, and a drifted one would be a plausible wrong value rather than an
-- error.
--
-- It sets defaults and BACKFILLS NOTHING. Every row already in the store keeps
-- the null it holds; only inserts that omit the column change. Filling those
-- rows would assert a value nobody observed.
begin;

do $$
begin
  if to_regclass('pennsync_records.patient') is null then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_STORE_REQUIRED';
  end if;
end $$;

do $$
declare v_admin text := current_user;
begin
  if exists (select 1 from pg_catalog.pg_roles
    where rolname = 'pennsync_records_owner' and (rolsuper or rolbypassrls)) then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_MUST_NOT_BYPASS_RLS';
  end if;
  begin
    execute format('grant %I to current_user with set true', 'pennsync_records_owner');
  exception
    when syntax_error then execute format('grant %I to current_user', 'pennsync_records_owner');
    when others then null; -- already held, or not ours to grant; proven below
  end;
  begin
    execute format('set role %I', 'pennsync_records_owner');
    execute format('set role %I', v_admin);
  exception when others then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_NOT_ASSUMABLE';
  end;
end $$;

-- As the owner, because `alter table` is the owner's to run.
set local role "pennsync_records_owner";

alter table "pennsync_records"."ai_configuration" alter column "compliance_priority" set default 'medicare';
alter table "pennsync_records"."ai_configuration" alter column "suggestion_aggressiveness" set default 'moderate';
alter table "pennsync_records"."ai_configuration" alter column "is_active" set default true;
alter table "pennsync_records"."ai_configuration" alter column "ai_verbosity" set default 'balanced';
alter table "pennsync_records"."ai_configuration" alter column "clinical_terminology" set default 'standard';
alter table "pennsync_records"."ai_configuration" alter column "enable_oasis_analysis" set default true;
alter table "pennsync_records"."ai_configuration" alter column "enable_auto_summarization" set default true;
alter table "pennsync_records"."ai_configuration" alter column "enable_compliance_checking" set default true;
alter table "pennsync_records"."ai_configuration" alter column "enable_care_plan_suggestions" set default true;
alter table "pennsync_records"."ai_configuration" alter column "enable_task_generation" set default true;
alter table "pennsync_records"."ai_configuration" alter column "enable_proactive_suggestions" set default false;
alter table "pennsync_records"."ai_configuration" alter column "auto_enhance_on_completion" set default false;
alter table "pennsync_records"."ai_configuration" alter column "preferred_note_style" set default 'narrative';
alter table "pennsync_records"."ai_configuration" alter column "include_assessment_details" set default true;
alter table "pennsync_records"."ai_configuration" alter column "include_teaching_points" set default true;
alter table "pennsync_records"."ai_configuration" alter column "show_confidence_scores" set default false;
alter table "pennsync_records"."ai_feedback" alter column "is_processed" set default false;
alter table "pennsync_records"."ai_knowledge_base" alter column "usage_count" set default 0;
alter table "pennsync_records"."ai_knowledge_base" alter column "effectiveness_score" set default 0;
alter table "pennsync_records"."ai_knowledge_base" alter column "is_active" set default true;
alter table "pennsync_records"."ai_learning_pattern" alter column "occurrences" set default 1;
alter table "pennsync_records"."ai_learning_pattern" alter column "successful_applications" set default 0;
alter table "pennsync_records"."ai_learning_pattern" alter column "is_active" set default true;
alter table "pennsync_records"."ai_model_configuration" alter column "model" set default 'gpt-4o';
alter table "pennsync_records"."ai_model_configuration" alter column "temperature" set default 0.3;
alter table "pennsync_records"."ai_model_configuration" alter column "max_tokens" set default 2500;
alter table "pennsync_records"."ai_model_configuration" alter column "is_active" set default true;
alter table "pennsync_records"."ai_model_configuration" alter column "is_ab_test" set default false;
alter table "pennsync_records"."ai_model_configuration" alter column "ab_test_weight" set default 50;
alter table "pennsync_records"."adr_audit_case" alter column "status" set default 'letter_uploaded';
alter table "pennsync_records"."adr_audit_case" alter column "audit_type" set default 'other';
alter table "pennsync_records"."adr_audit_case" alter column "outcome" set default 'pending';
alter table "pennsync_records"."agency" alter column "max_users" set default 10;
alter table "pennsync_records"."agency" alter column "price_per_user" set default 29.99;
alter table "pennsync_records"."agency" alter column "status" set default 'active';
alter table "pennsync_records"."agency" alter column "billing_cycle" set default 'monthly';
alter table "pennsync_records"."agency" alter column "current_user_count" set default 0;
alter table "pennsync_records"."agency" alter column "total_billed_amount" set default 0;
alter table "pennsync_records"."agency" alter column "enabled_features" set default '["SmartNoteAssistant","MedicalScribe","ClinicalDecisionSupport","OASIS","Compliance","CarePlanManagement","DocumentGenerator","BillingOptimization"]'::jsonb;
alter table "pennsync_records"."agency" alter column "auto_billing_enabled" set default true;
alter table "pennsync_records"."agency" alter column "primary_color" set default '#3b82f6';
alter table "pennsync_records"."agency_compliance_rule" alter column "severity" set default 'medium';
alter table "pennsync_records"."agency_compliance_rule" alter column "auto_fix_available" set default false;
alter table "pennsync_records"."agency_compliance_rule" alter column "is_active" set default true;
alter table "pennsync_records"."agency_feature_access" alter column "feature_tier" set default 'professional';
alter table "pennsync_records"."agency_invitation" alter column "status" set default 'pending';
alter table "pennsync_records"."agency_invoice" alter column "tax_amount" set default 0;
alter table "pennsync_records"."agency_invoice" alter column "status" set default 'draft';
alter table "pennsync_records"."agency_membership" alter column "status" set default 'pending';
alter table "pennsync_records"."agency_membership" alter column "version" set default 1;
alter table "pennsync_records"."agency_settings" alter column "oasis_response_schema_v2_enabled" set default false;
alter table "pennsync_records"."agency_settings" alter column "oasis_response_writes_disabled" set default false;
alter table "pennsync_records"."agency_settings" alter column "wage_index" set default 1;
alter table "pennsync_records"."agency_settings" alter column "avg_staff_hourly_rate" set default 45;
alter table "pennsync_records"."agency_settings" alter column "training_cost_per_hour" set default 35;
alter table "pennsync_records"."agency_settings" alter column "documentation_time_per_episode" set default 0.5;
alter table "pennsync_records"."agency_settings" alter column "audit_staff_hourly_rate" set default 50;
alter table "pennsync_records"."agency_settings" alter column "avg_episodes_per_year" set default 50;
alter table "pennsync_records"."agency_settings" alter column "pennsync_is_system_of_record" set default false;
alter table "pennsync_records"."agency_settings" alter column "is_enterprise" set default false;
alter table "pennsync_records"."agency_settings" alter column "ai_learning_enabled" set default true;
alter table "pennsync_records"."agency_settings" alter column "agency_wide_learning" set default false;
alter table "pennsync_records"."agency_settings" alter column "ai_model_preference" set default 'balanced';
alter table "pennsync_records"."agency_settings" alter column "min_confidence_threshold" set default 70;
alter table "pennsync_records"."agency_settings" alter column "share_learnings_across_providers" set default true;
alter table "pennsync_records"."agency_settings" alter column "auto_apply_best_practices" set default false;
alter table "pennsync_records"."agency_settings" alter column "custom_templates_count" set default 0;
alter table "pennsync_records"."agency_settings" alter column "tcpa_quiet_hours_enabled" set default true;
alter table "pennsync_records"."agency_settings" alter column "tcpa_quiet_start_hour" set default 8;
alter table "pennsync_records"."agency_settings" alter column "tcpa_quiet_end_hour" set default 21;
alter table "pennsync_records"."agency_settings" alter column "fax_receiving_enabled" set default false;
alter table "pennsync_records"."agency_settings" alter column "sms_messaging_enabled" set default true;
alter table "pennsync_records"."agency_settings" alter column "voicemail_enabled" set default false;
alter table "pennsync_records"."agency_settings" alter column "allow_international" set default false;
alter table "pennsync_records"."agency_settings" alter column "business_hours_enabled" set default false;
alter table "pennsync_records"."agency_settings" alter column "business_hours_timezone" set default 'America/New_York';
alter table "pennsync_records"."agency_settings" alter column "after_hours_call_action" set default 'transfer';
alter table "pennsync_records"."agency_settings" alter column "after_hours_sms_auto_reply_enabled" set default true;
alter table "pennsync_records"."agency_settings" alter column "a2p_10dlc_status" set default 'not_registered';
alter table "pennsync_records"."alert_trigger_rule" alter column "alert_severity" set default 'moderate';
alter table "pennsync_records"."alert_trigger_rule" alter column "notification_channels" set default '["in_app"]'::jsonb;
alter table "pennsync_records"."alert_trigger_rule" alter column "is_active" set default true;
alter table "pennsync_records"."alert_trigger_rule" alter column "applies_to_patients" set default 'all';
alter table "pennsync_records"."alert_trigger_rule" alter column "cooldown_hours" set default 24;
alter table "pennsync_records"."alert_trigger_rule" alter column "trigger_count" set default 0;
alter table "pennsync_records"."announcement" alter column "type" set default 'info';
alter table "pennsync_records"."announcement" alter column "is_active" set default true;
alter table "pennsync_records"."announcement" alter column "priority" set default 0;
alter table "pennsync_records"."appointment_form" alter column "status" set default 'sent';
alter table "pennsync_records"."appointment_form" alter column "reminder_count" set default 0;
alter table "pennsync_records"."approval_request" alter column "status" set default 'pending';
alter table "pennsync_records"."approval_request" alter column "priority" set default 'medium';
alter table "pennsync_records"."automatic_care_plan_trigger" alter column "care_type" set default 'both';
alter table "pennsync_records"."automatic_care_plan_trigger" alter column "priority" set default 'medium';
alter table "pennsync_records"."automatic_care_plan_trigger" alter column "days_until_target" set default 60;
alter table "pennsync_records"."automatic_care_plan_trigger" alter column "is_active" set default true;
alter table "pennsync_records"."bi_integration" alter column "sync_status" set default 'active';
alter table "pennsync_records"."bi_integration" alter column "records_synced" set default 0;
alter table "pennsync_records"."bi_integration" alter column "is_active" set default true;
alter table "pennsync_records"."billing" alter column "billing_status" set default 'draft';
alter table "pennsync_records"."care_coordination_alert" alter column "team_meeting_suggested" set default false;
alter table "pennsync_records"."care_coordination_alert" alter column "status" set default 'active';
alter table "pennsync_records"."care_plan" alter column "status" set default 'active';
alter table "pennsync_records"."care_plan_proposal" alter column "priority" set default 'routine';
alter table "pennsync_records"."care_plan_proposal" alter column "status" set default 'pending_review';
alter table "pennsync_records"."care_setting" alter column "requires_oasis" set default false;
alter table "pennsync_records"."care_setting" alter column "requires_prior_auth" set default false;
alter table "pennsync_records"."care_setting" alter column "is_active" set default true;
alter table "pennsync_records"."care_setting" alter column "is_sample" set default false;
alter table "pennsync_records"."clinical_event" alter column "requires_followup" set default false;
alter table "pennsync_records"."clinical_event" alter column "verified" set default false;
alter table "pennsync_records"."clinical_library_folder" alter column "color" set default 'blue';
alter table "pennsync_records"."clinical_library_folder" alter column "order" set default 0;
alter table "pennsync_records"."clinical_library_folder" alter column "is_agency_wide" set default false;
alter table "pennsync_records"."clinical_library_template" alter column "template_type" set default 'generic';
alter table "pennsync_records"."clinical_library_template" alter column "requires_patient_data" set default false;
alter table "pennsync_records"."clinical_library_template" alter column "is_active" set default true;
alter table "pennsync_records"."clinical_library_template" alter column "usage_count" set default 0;
alter table "pennsync_records"."clinical_library_template" alter column "is_agency_wide" set default false;
alter table "pennsync_records"."clinical_pathway" alter column "is_active" set default true;
alter table "pennsync_records"."clinical_pathway" alter column "usage_count" set default 0;
alter table "pennsync_records"."compliance_audit" alter column "status" set default 'pending_review';
alter table "pennsync_records"."compliance_audit" alter column "audit_type" set default 'automated';
alter table "pennsync_records"."compliance_rule" alter column "severity" set default 'medium';
alter table "pennsync_records"."compliance_rule" alter column "applies_to_care_type" set default 'both';
alter table "pennsync_records"."compliance_rule" alter column "is_active" set default true;
alter table "pennsync_records"."compliance_violation" alter column "status" set default 'open';
alter table "pennsync_records"."compliance_violation" alter column "auto_fix_available" set default false;
alter table "pennsync_records"."compliance_violation" alter column "detection_method" set default 'automated';
alter table "pennsync_records"."content_scope_binding" alter column "status" set default 'quarantined';
alter table "pennsync_records"."content_scope_binding" alter column "version" set default 1;
alter table "pennsync_records"."custom_validation_rule" alter column "severity" set default 'error';
alter table "pennsync_records"."custom_validation_rule" alter column "is_active" set default true;
alter table "pennsync_records"."data_archive_policy" alter column "is_automatic" set default false;
alter table "pennsync_records"."data_archive_policy" alter column "records_archived" set default 0;
alter table "pennsync_records"."data_archive_policy" alter column "is_active" set default true;
alter table "pennsync_records"."data_archive_policy" alter column "storage_location" set default 'cold_storage';
alter table "pennsync_records"."discharge_summary" alter column "physician_notified" set default false;
alter table "pennsync_records"."discharge_summary" alter column "status" set default 'draft';
alter table "pennsync_records"."document" alter column "is_sensitive" set default false;
alter table "pennsync_records"."document" alter column "clinician_signed" set default false;
alter table "pennsync_records"."document" alter column "patient_signed" set default false;
alter table "pennsync_records"."document" alter column "is_signed" set default false;
alter table "pennsync_records"."document" alter column "is_locked" set default false;
alter table "pennsync_records"."document_automation_workflow" alter column "is_active" set default true;
alter table "pennsync_records"."document_automation_workflow" alter column "trigger_count" set default 0;
alter table "pennsync_records"."document_package" alter column "authority_version" set default 1;
alter table "pennsync_records"."document_package" alter column "status" set default 'pending';
alter table "pennsync_records"."document_package" alter column "auto_reminder_enabled" set default true;
alter table "pennsync_records"."document_package" alter column "reminder_days_before" set default 3;
alter table "pennsync_records"."document_record" alter column "version_number" set default 1;
alter table "pennsync_records"."document_record" alter column "is_signed" set default false;
alter table "pennsync_records"."document_record" alter column "signature_status" set default 'unsigned';
alter table "pennsync_records"."document_record" alter column "is_archived" set default false;
alter table "pennsync_records"."document_template" alter column "is_system_template" set default false;
alter table "pennsync_records"."document_template" alter column "is_public" set default false;
alter table "pennsync_records"."document_template" alter column "usage_count" set default 0;
alter table "pennsync_records"."document_template" alter column "ai_generated" set default false;
alter table "pennsync_records"."document_template" alter column "auto_suggest_materials" set default true;
alter table "pennsync_records"."document_tenant_binding" alter column "version" set default 2;
alter table "pennsync_records"."document_version" alter column "is_current" set default true;
alter table "pennsync_records"."document_version" alter column "signatures_carried_forward" set default false;
alter table "pennsync_records"."document_version" alter column "invalidated_previous_signatures" set default true;
alter table "pennsync_records"."documentation_template" alter column "is_agency_wide" set default true;
alter table "pennsync_records"."education_material" alter column "reading_level" set default 'middle_school';
alter table "pennsync_records"."education_material" alter column "language" set default 'english';
alter table "pennsync_records"."education_material" alter column "is_template" set default true;
alter table "pennsync_records"."education_material" alter column "usage_count" set default 0;
alter table "pennsync_records"."education_material" alter column "is_published" set default true;
alter table "pennsync_records"."education_material" alter column "version" set default 1;
alter table "pennsync_records"."embed_config" alter column "show_signature_fields" set default false;
alter table "pennsync_records"."embed_config" alter column "show_metadata" set default false;
alter table "pennsync_records"."embed_config" alter column "width" set default '100%';
alter table "pennsync_records"."embed_config" alter column "height" set default '600px';
alter table "pennsync_records"."embed_config" alter column "allow_download" set default false;
alter table "pennsync_records"."embed_config" alter column "allow_print" set default false;
alter table "pennsync_records"."embed_config" alter column "view_count" set default 0;
alter table "pennsync_records"."embed_config" alter column "status" set default 'active';
alter table "pennsync_records"."employee_payroll_profile" alter column "service_type" set default 'home_health';
alter table "pennsync_records"."employee_payroll_profile" alter column "earns_points" set default false;
alter table "pennsync_records"."employee_payroll_profile" alter column "phone_reimbursement" set default 0;
alter table "pennsync_records"."employee_payroll_profile" alter column "active" set default true;
alter table "pennsync_records"."face_to_face_encounter" alter column "validation_status" set default 'needs_review';
alter table "pennsync_records"."facility_documentation_rule" alter column "condition_type" set default 'always';
alter table "pennsync_records"."facility_documentation_rule" alter column "severity" set default 'high';
alter table "pennsync_records"."facility_documentation_rule" alter column "is_active" set default true;
alter table "pennsync_records"."feature_package" alter column "is_custom" set default false;
alter table "pennsync_records"."feature_package" alter column "tier" set default 'professional';
alter table "pennsync_records"."feature_package" alter column "is_active" set default true;
alter table "pennsync_records"."feature_toggle" alter column "enabled" set default true;
alter table "pennsync_records"."fleet_service_entry" alter column "review_status" set default 'pending';
alter table "pennsync_records"."fleet_vehicle" alter column "status" set default 'active';
alter table "pennsync_records"."fleet_vehicle" alter column "version" set default 1;
alter table "pennsync_records"."form_template" alter column "send_days_before" set default 3;
alter table "pennsync_records"."form_template" alter column "is_active" set default true;
alter table "pennsync_records"."generated_document" alter column "status" set default 'draft';
alter table "pennsync_records"."health_record" alter column "clinical_significance" set default 'moderate';
alter table "pennsync_records"."health_record" alter column "status" set default 'active';
alter table "pennsync_records"."health_record" alter column "is_encrypted" set default true;
alter table "pennsync_records"."health_record" alter column "confidential_flag" set default false;
alter table "pennsync_records"."immunization" alter column "is_complete" set default false;
alter table "pennsync_records"."incident" alter column "physician_notified" set default false;
alter table "pennsync_records"."incident" alter column "office_notified" set default false;
alter table "pennsync_records"."incident" alter column "status" set default 'reported';
alter table "pennsync_records"."incident" alter column "is_sample" set default false;
alter table "pennsync_records"."incident" alter column "alert_triggered" set default false;
alter table "pennsync_records"."incident" alter column "state_reportable" set default false;
alter table "pennsync_records"."insurance_provider" alter column "is_active" set default true;
alter table "pennsync_records"."intervention_log" alter column "outcome_status" set default 'pending';
alter table "pennsync_records"."intervention_log" alter column "requires_follow_up" set default false;
alter table "pennsync_records"."invitation_settings" alter column "expiry_days" set default 7;
alter table "pennsync_records"."invitation_settings" alter column "cleanup_after_days" set default 30;
alter table "pennsync_records"."invitation_settings" alter column "notify_before_cleanup" set default true;
alter table "pennsync_records"."invoice" alter column "paid_amount" set default 0;
alter table "pennsync_records"."invoice" alter column "status" set default 'pending';
alter table "pennsync_records"."invoice" alter column "patient_email_sent" set default false;
alter table "pennsync_records"."invoice" alter column "insurance_billed" set default false;
alter table "pennsync_records"."invoice" alter column "reminders_sent" set default 0;
alter table "pennsync_records"."invoice" alter column "billing_model" set default 'fee_for_service';
alter table "pennsync_records"."learned_format_pattern" alter column "usage_count" set default 1;
alter table "pennsync_records"."learned_format_pattern" alter column "is_active" set default true;
alter table "pennsync_records"."library_document" alter column "category" set default 'other';
alter table "pennsync_records"."library_document" alter column "is_active" set default true;
alter table "pennsync_records"."medical_code" alter column "status" set default 'pending_review';
alter table "pennsync_records"."medicare_compliance_rule" alter column "severity" set default 'high';
alter table "pennsync_records"."medicare_compliance_rule" alter column "pennsylvania_specific" set default false;
alter table "pennsync_records"."medicare_compliance_rule" alter column "is_active" set default true;
alter table "pennsync_records"."medicare_guideline" alter column "is_active" set default true;
alter table "pennsync_records"."medication" alter column "status" set default 'active';
alter table "pennsync_records"."medication_reconciliation" alter column "status" set default 'pending_review';
alter table "pennsync_records"."medication_reconciliation" alter column "physician_notified" set default false;
alter table "pennsync_records"."medication_reconciliation" alter column "patient_education_provided" set default false;
alter table "pennsync_records"."medication_reconciliation" alter column "total_discrepancies" set default 0;
alter table "pennsync_records"."medication_reconciliation" alter column "critical_discrepancies" set default 0;
alter table "pennsync_records"."new_feature" alter column "icon" set default 'sparkles';
alter table "pennsync_records"."new_feature" alter column "is_active" set default true;
alter table "pennsync_records"."new_feature" alter column "priority" set default 0;
alter table "pennsync_records"."note_template" alter column "is_system_template" set default false;
alter table "pennsync_records"."note_template" alter column "is_favorite" set default false;
alter table "pennsync_records"."notification" alter column "authority_state" set default 'active';
alter table "pennsync_records"."notification" alter column "priority" set default 'medium';
alter table "pennsync_records"."notification" alter column "is_read" set default false;
alter table "pennsync_records"."notification" alter column "email_sent" set default false;
alter table "pennsync_records"."notification" alter column "push_sent" set default false;
alter table "pennsync_records"."notification" alter column "dismissed" set default false;
alter table "pennsync_records"."notification_preference" alter column "email_notifications_enabled" set default true;
alter table "pennsync_records"."notification_preference" alter column "in_app_notifications_enabled" set default true;
alter table "pennsync_records"."notification_preference" alter column "push_notifications_enabled" set default false;
alter table "pennsync_records"."notification_preference" alter column "digest_mode" set default 'instant';
alter table "pennsync_records"."notification_preference" alter column "sound_enabled" set default true;
alter table "pennsync_records"."notification_preferences" alter column "onboarding_emails" set default true;
alter table "pennsync_records"."notification_preferences" alter column "feature_announcements" set default true;
alter table "pennsync_records"."notification_preferences" alter column "subscription_reminders" set default true;
alter table "pennsync_records"."notification_preferences" alter column "abandoned_cart_recovery" set default true;
alter table "pennsync_records"."notification_preferences" alter column "marketing_emails" set default true;
alter table "pennsync_records"."notification_preferences" alter column "product_updates" set default true;
alter table "pennsync_records"."notification_preferences" alter column "weekly_digest" set default false;
alter table "pennsync_records"."notification_preferences" alter column "email_frequency" set default 'immediate';
alter table "pennsync_records"."notification_rule" alter column "is_active" set default true;
alter table "pennsync_records"."notification_rule" alter column "trigger_count" set default 0;
alter table "pennsync_records"."nurse_goal" alter column "status" set default 'active';
alter table "pennsync_records"."nurse_goal" alter column "priority" set default 'medium';
alter table "pennsync_records"."ocr_feedback" alter column "applied_to_training" set default false;
alter table "pennsync_records"."ocr_training_session" alter column "status" set default 'processing';
alter table "pennsync_records"."pdf_template" alter column "version" set default '1.0';
alter table "pennsync_records"."pdf_template" alter column "is_active" set default true;
alter table "pennsync_records"."pdf_template" alter column "is_packet" set default false;
alter table "pennsync_records"."pdf_template" alter column "document_count" set default 1;
alter table "pennsync_records"."pdf_template" alter column "usage_count" set default 0;
alter table "pennsync_records"."patient" alter column "care_type" set default 'home_health';
alter table "pennsync_records"."patient" alter column "status" set default 'active';
alter table "pennsync_records"."patient" alter column "is_sample" set default false;
alter table "pennsync_records"."patient" alter column "is_archived" set default false;
alter table "pennsync_records"."patient_alert" alter column "status" set default 'active';
alter table "pennsync_records"."patient_alert" alter column "flagged_urgent" set default false;
alter table "pennsync_records"."patient_billing_info" alter column "payment_plan_active" set default false;
alter table "pennsync_records"."patient_billing_info" alter column "credit_limit" set default 0;
alter table "pennsync_records"."patient_document" alter column "processing_status" set default 'pending';
alter table "pennsync_records"."patient_document" alter column "is_reviewed" set default false;
alter table "pennsync_records"."patient_education_assignment" alter column "status" set default 'assigned';
alter table "pennsync_records"."patient_education_assignment" alter column "priority" set default 'medium';
alter table "pennsync_records"."patient_education_delivery" alter column "content_type" set default 'text';
alter table "pennsync_records"."patient_education_delivery" alter column "reading_level" set default 'basic';
alter table "pennsync_records"."patient_education_delivery" alter column "delivery_status" set default 'pending';
alter table "pennsync_records"."patient_education_delivery" alter column "teach_back_confirmation" set default false;
alter table "pennsync_records"."patient_education_delivery" alter column "follow_up_needed" set default false;
alter table "pennsync_records"."patient_education_draft" alter column "reading_level" set default 'simple';
alter table "pennsync_records"."patient_education_draft" alter column "status" set default 'draft';
alter table "pennsync_records"."patient_education_material" alter column "content_type" set default 'structured';
alter table "pennsync_records"."patient_education_material" alter column "language" set default 'en';
alter table "pennsync_records"."patient_education_material" alter column "reading_level" set default 'simple';
alter table "pennsync_records"."patient_education_material" alter column "patient_specific" set default false;
alter table "pennsync_records"."patient_education_material" alter column "is_approved" set default true;
alter table "pennsync_records"."patient_education_material" alter column "view_count" set default 0;
alter table "pennsync_records"."patient_pathway_assignment" alter column "status" set default 'active';
alter table "pennsync_records"."patient_recommendation" alter column "priority" set default 'medium';
alter table "pennsync_records"."patient_recommendation" alter column "status" set default 'pending';
alter table "pennsync_records"."patient_risk_assessment" alter column "status" set default 'active';
alter table "pennsync_records"."pending_patient_update" alter column "status" set default 'pending';
alter table "pennsync_records"."pending_patient_update" alter column "conflict_detected" set default false;
alter table "pennsync_records"."personnel_credential" alter column "status" set default 'pending_approval';
alter table "pennsync_records"."physician" alter column "accepts_home_health" set default true;
alter table "pennsync_records"."physician" alter column "accepts_hospice" set default false;
alter table "pennsync_records"."physician" alter column "preferred_contact_method" set default 'fax';
alter table "pennsync_records"."physician" alter column "is_active" set default true;
alter table "pennsync_records"."physician" alter column "referral_count" set default 0;
alter table "pennsync_records"."physician_agency_profile" alter column "status" set default 'quarantined';
alter table "pennsync_records"."physician_agency_profile" alter column "referral_count" set default 0;
alter table "pennsync_records"."physician_agency_profile" alter column "version" set default 1;
alter table "pennsync_records"."policy_acknowledgment" alter column "status" set default 'assigned';
alter table "pennsync_records"."policy_acknowledgment" alter column "acknowledged" set default false;
alter table "pennsync_records"."policy_library" alter column "status" set default 'active';
alter table "pennsync_records"."provider_dashboard_customization" alter column "dashboard_layout" set default 'default';
alter table "pennsync_records"."provider_dashboard_customization" alter column "default_view" set default 'my_patients';
alter table "pennsync_records"."provider_dashboard_customization" alter column "theme" set default 'light';
alter table "pennsync_records"."provider_facility_assignment" alter column "is_primary_facility" set default false;
alter table "pennsync_records"."provider_facility_assignment" alter column "is_active" set default true;
alter table "pennsync_records"."provider_facility_assignment" alter column "is_on_call" set default false;
alter table "pennsync_records"."provider_patient_assignment" alter column "assignment_type" set default 'primary';
alter table "pennsync_records"."provider_patient_assignment" alter column "is_active" set default true;
alter table "pennsync_records"."provider_patient_assignment" alter column "access_level" set default 'full';
alter table "pennsync_records"."provider_permission" alter column "is_allowed" set default true;
alter table "pennsync_records"."provider_permission" alter column "custom_override" set default false;
alter table "pennsync_records"."provider_practice_info" alter column "include_header" set default true;
alter table "pennsync_records"."provider_practice_info" alter column "include_signature" set default true;
alter table "pennsync_records"."provider_preferences" alter column "is_active" set default true;
alter table "pennsync_records"."provider_settings" alter column "is_active" set default true;
alter table "pennsync_records"."provider_specialization" alter column "expertise_level" set default 'intermediate';
alter table "pennsync_records"."provider_specialization" alter column "is_primary" set default false;
alter table "pennsync_records"."provider_specialization" alter column "is_active" set default true;
alter table "pennsync_records"."provider_usage_pattern" alter column "total_notes_generated" set default 0;
alter table "pennsync_records"."referral" alter column "priority" set default 'normal';
alter table "pennsync_records"."referral" alter column "status" set default 'new';
alter table "pennsync_records"."regulatory_update" alter column "status" set default 'pending_review';
alter table "pennsync_records"."reminder_log" alter column "reminder_type" set default 'pre_due';
alter table "pennsync_records"."reminder_log" alter column "status" set default 'sent';
alter table "pennsync_records"."report_template" alter column "is_public" set default false;
alter table "pennsync_records"."report_template" alter column "usage_count" set default 0;
alter table "pennsync_records"."risk_alert" alter column "alert_on_increase" set default true;
alter table "pennsync_records"."risk_alert" alter column "alert_on_decrease" set default false;
alter table "pennsync_records"."risk_alert" alter column "is_active" set default true;
alter table "pennsync_records"."risk_alert" alter column "notification_method" set default 'in_app';
alter table "pennsync_records"."scheduled_report" alter column "format" set default 'pdf';
alter table "pennsync_records"."scheduled_report" alter column "is_active" set default true;
alter table "pennsync_records"."scheduled_report" alter column "run_count" set default 0;
alter table "pennsync_records"."sent_education_material" alter column "patient_acknowledged" set default false;
alter table "pennsync_records"."service_code" alter column "is_active" set default true;
alter table "pennsync_records"."service_code" alter column "requires_authorization" set default false;
alter table "pennsync_records"."session_timeout" alter column "timeout_minutes" set default 15;
alter table "pennsync_records"."session_timeout" alter column "warning_shown" set default false;
alter table "pennsync_records"."session_timeout" alter column "auto_logout" set default true;
alter table "pennsync_records"."shared_document" alter column "current_version" set default 1;
alter table "pennsync_records"."shared_document" alter column "status" set default 'active';
alter table "pennsync_records"."shared_phrase_library" alter column "usage_count" set default 0;
alter table "pennsync_records"."shared_phrase_library" alter column "is_best_practice" set default false;
alter table "pennsync_records"."suggested_intervention" alter column "priority" set default 'high';
alter table "pennsync_records"."suggested_intervention" alter column "status" set default 'pending_review';
alter table "pennsync_records"."supply_item" alter column "current_quantity" set default 0;
alter table "pennsync_records"."supply_item" alter column "status" set default 'in_stock';
alter table "pennsync_records"."supply_low_stock_alert" alter column "status" set default 'active';
alter table "pennsync_records"."supply_low_stock_alert" alter column "reorder_task_created" set default false;
alter table "pennsync_records"."supply_usage_log" alter column "extracted_from_note" set default false;
alter table "pennsync_records"."task" alter column "priority" set default 'medium';
alter table "pennsync_records"."task" alter column "status" set default 'pending';
alter table "pennsync_records"."task" alter column "source" set default 'manual';
alter table "pennsync_records"."task" alter column "is_recurring" set default false;
alter table "pennsync_records"."task" alter column "recurrence_interval" set default 1;
alter table "pennsync_records"."task" alter column "is_sample" set default false;
alter table "pennsync_records"."team_note" alter column "flagged" set default false;
alter table "pennsync_records"."terminology_glossary" alter column "language" set default 'en';
alter table "pennsync_records"."terminology_glossary" alter column "is_active" set default true;
alter table "pennsync_records"."time_off_request" alter column "request_type" set default 'vacation';
alter table "pennsync_records"."time_off_request" alter column "half_day" set default false;
alter table "pennsync_records"."time_off_request" alter column "status" set default 'pending';
alter table "pennsync_records"."timesheet" alter column "service_type" set default 'home_health';
alter table "pennsync_records"."timesheet" alter column "regular_points" set default 0;
alter table "pennsync_records"."timesheet" alter column "emergency_visit_points" set default 0;
alter table "pennsync_records"."timesheet" alter column "regular_hours" set default 0;
alter table "pennsync_records"."timesheet" alter column "overtime_hours" set default 0;
alter table "pennsync_records"."timesheet" alter column "vacation_hours" set default 0;
alter table "pennsync_records"."timesheet" alter column "holiday_hours" set default 0;
alter table "pennsync_records"."timesheet" alter column "on_call_hours" set default 0;
alter table "pennsync_records"."timesheet" alter column "on_call_visits" set default 0;
alter table "pennsync_records"."timesheet" alter column "miles" set default 0;
alter table "pennsync_records"."timesheet" alter column "reimbursement" set default 0;
alter table "pennsync_records"."timesheet" alter column "auto_pto_hours" set default 0;
alter table "pennsync_records"."timesheet" alter column "phone_reimbursement" set default 0;
alter table "pennsync_records"."timesheet" alter column "entry_mode" set default 'bulk';
alter table "pennsync_records"."timesheet" alter column "status" set default 'draft';
alter table "pennsync_records"."user" alter column "role" set default 'user';
alter table "pennsync_records"."user" alter column "credential_type" set default 'RN';
alter table "pennsync_records"."user" alter column "service_type" set default 'home_health';
alter table "pennsync_records"."user" alter column "preferred_language" set default 'en-US';
alter table "pennsync_records"."user" alter column "two_factor_enabled" set default false;
alter table "pennsync_records"."user" alter column "data_retention_preference" set default 'save';
alter table "pennsync_records"."user" alter column "agency_role" set default 'nurse';
alter table "pennsync_records"."user" alter column "is_active" set default true;
alter table "pennsync_records"."user" alter column "is_approved" set default false;
alter table "pennsync_records"."user" alter column "is_manager" set default false;
alter table "pennsync_records"."user" alter column "staff_role" set default 'nurse';
alter table "pennsync_records"."user" alter column "scheduled_off_duty_recurring" set default false;
alter table "pennsync_records"."user" alter column "ai_content_agreement_accepted" set default false;
alter table "pennsync_records"."user_invitation" alter column "role" set default 'user';
alter table "pennsync_records"."user_invitation" alter column "care_scope" set default 'home_health';
alter table "pennsync_records"."user_invitation" alter column "staff_role" set default 'nurse';
alter table "pennsync_records"."user_invitation" alter column "status" set default 'pending';
alter table "pennsync_records"."user_invitation" alter column "resend_count" set default 0;
alter table "pennsync_records"."user_learned_pattern" alter column "frequency" set default 1;
alter table "pennsync_records"."user_learned_pattern" alter column "suggestions_accepted" set default 0;
alter table "pennsync_records"."user_learned_pattern" alter column "suggestions_rejected" set default 0;
alter table "pennsync_records"."user_learned_pattern" alter column "is_active" set default true;
alter table "pennsync_records"."verification_code" alter column "purpose" set default 'authentication';
alter table "pennsync_records"."verification_code" alter column "verified" set default false;
alter table "pennsync_records"."visit" alter column "status" set default 'scheduled';
alter table "pennsync_records"."visit" alter column "family_update_sent" set default false;
alter table "pennsync_records"."visit" alter column "is_sample" set default false;
alter table "pennsync_records"."visit" alter column "documentation_source" set default 'smart_note';
alter table "pennsync_records"."visit" alter column "grounding_pending" set default false;
alter table "pennsync_records"."visit" alter column "emr_handoff_status" set default 'not_started';
alter table "pennsync_records"."visit_point_config" alter column "soc_points" set default 0;
alter table "pennsync_records"."visit_point_config" alter column "roc_points" set default 0;
alter table "pennsync_records"."visit_point_config" alter column "recert_points" set default 0;
alter table "pennsync_records"."visit_point_config" alter column "routine_points" set default 0;
alter table "pennsync_records"."visit_point_config" alter column "discharge_points" set default 0;
alter table "pennsync_records"."visit_point_config" alter column "active" set default true;

reset role;
commit;
