-- GENERATED by `node tools-read-purpose-policy.mjs --write`. Do not edit.
--
-- The authorized-visit purpose policies, as SQL.
--
-- Reading a visit is purpose-bound: a caller names a purpose, and the
-- purpose decides which fields are disclosed and which tenant roles may ask at
-- all. Those blocks are the authorization contract, and they are 16 purposes
-- long between them — so they are extracted from
-- `base44/functions/listAuthorizedVisits/entry.ts` and
-- `base44/functions/getAuthorizedVisit/entry.ts`
-- rather than retyped, and re-extracted by a test on every run. A dropped
-- field name here would widen or narrow a clinical disclosure with nothing to
-- notice it.
--
-- Two vocabularies, deliberately not merged: the list capability and the
-- single-read capability each declare their own purposes, so a purpose from
-- one is not a purpose in the other and `<prefix>_known` is how each contract
-- says so.
--
-- Every function here is pure, and none of them has any authorization: they
-- answer what a policy says, never who is asking. The contracts beside them
-- are hand-written and decide that, because a capability's authorization is
-- its own.
--
-- The action policies here belong to a capability that takes ONE named action
-- per call rather than a batch: 9 actions, of which this port serves
-- 4. What they carry is each action's INPUTS, because an action interprets
-- them rather than writing them; which columns move is the contract's. The
-- roles are the contract's too — the original decides them in code, and
-- inventing a data shape for a decision is not carrying it.
--
-- One divergence from the originals, and it is a narrowing: platform_owner is
-- admitted by 16 of the 16 purposes and actions there and by none
-- here. D14 and D22 removed the platform tier, `caller_tenant_role` can only
-- answer one of agency_admin, manager, clinician,
-- office_staff, social_worker, spiritual_care, and emitting a branch nothing
-- can take would read like a tier that still exists. Every purpose and every
-- action still admits somebody without it; the generator refuses to render if
-- one would not.
begin;

do $$
begin
  if to_regclass('pennsync_records.visit') is null
    or to_regprocedure('pennsync_records.caller_tenant_role(text)') is null then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_STORE_REQUIRED';
  end if;
end $$;

do $$
declare v_admin text := current_user;
begin
  if exists (select 1 from pg_catalog.pg_roles
    where rolname = 'pennsync_records_owner' and (rolsuper or rolbypassrls)) then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_MUST_NOT_BYPASS_RLS';
  end if;
  begin
    execute format('grant %I to current_user with set true', 'pennsync_records_owner');
  exception
    when syntax_error then execute format('grant %I to current_user', 'pennsync_records_owner');
    when others then null; -- already held, or not ours to grant; proven below
  end;
  begin
    execute format('set role %I', 'pennsync_records_owner');
    execute format('set role %I', v_admin);
  exception when others then
    raise exception using errcode='42501',message='PENNSYNC_RECORD_OWNER_NOT_ASSUMABLE';
  end;
end $$;

-- Owned by the record owner, like everything the contracts call, so a caller
-- cannot reach them and the contracts can.
set local role "pennsync_records_owner";

-- From `base44/functions/listAuthorizedVisits/entry.ts`: 13 purposes.
create function "pennsync_records"."visit_list_purpose_known"(p_purpose text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'activity' then true
    when 'ai_tagging' then true
    when 'clinical_insights' then true
    when 'compliance_monitoring' then true
    when 'compliance_review' then true
    when 'data_quality' then true
    when 'deduplication' then true
    when 'documentation' then true
    when 'hospitalization_risk' then true
    when 'operations_analytics' then true
    when 'reporting' then true
    when 'schedule' then true
    when 'vitals_trend' then true
    else false end
$policy$;

create function "pennsync_records"."visit_list_purpose_admits"(p_purpose text, p_role text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'activity' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'ai_tagging' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'clinical_insights' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'compliance_monitoring' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'compliance_review' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'data_quality' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'deduplication' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'documentation' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'hospitalization_risk' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'operations_analytics' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'reporting' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'schedule' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'vitals_trend' then p_role in ('agency_admin', 'clinician', 'manager')
    else false end
$policy$;

create function "pennsync_records"."visit_list_purpose_page_size"(p_purpose text) returns integer
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'activity' then 50
    when 'ai_tagging' then 25
    when 'clinical_insights' then 50
    when 'compliance_monitoring' then 25
    when 'compliance_review' then 25
    when 'data_quality' then 25
    when 'deduplication' then 25
    when 'documentation' then 25
    when 'hospitalization_risk' then 25
    when 'operations_analytics' then 50
    when 'reporting' then 25
    when 'schedule' then 50
    when 'vitals_trend' then 50
    else null end
$policy$;

-- Stable rather than immutable: a date or timestamp reaches JSON through the
-- session's DateStyle and TimeZone, so this is not constant-foldable.
create function "pennsync_records"."visit_list_purpose_row"(
  p_purpose text, p "pennsync_records"."visit") returns jsonb
  language sql stable set search_path = '' as $policy$
  select case p_purpose
    when 'activity' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'created_date', p."created_date",
      'updated_date', p."updated_date")
    when 'ai_tagging' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'nurse_notes', p."nurse_notes",
      'ai_tags', p."ai_tags",
      'updated_date', p."updated_date")
    when 'clinical_insights' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'vital_signs', p."vital_signs",
      'created_by', p."created_by",
      'updated_date', p."updated_date")
    when 'compliance_monitoring' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'nurse_notes', p."nurse_notes",
      'compliance_score', p."compliance_score",
      'compliance_issues', p."compliance_issues",
      'homebound_status_verified', p."homebound_status_verified",
      'skilled_intervention_documented', p."skilled_intervention_documented",
      'homebound_justification', p."homebound_justification",
      'grounding_pending', p."grounding_pending",
      'created_by', p."created_by",
      'updated_date', p."updated_date")
    when 'compliance_review' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'compliance_score', p."compliance_score",
      'grounding_pending', p."grounding_pending",
      'updated_date', p."updated_date")
    when 'data_quality' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'nurse_notes', p."nurse_notes",
      'vital_signs', p."vital_signs",
      'homebound_justification', p."homebound_justification",
      'updated_date', p."updated_date")
    when 'deduplication' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'created_by', p."created_by",
      'created_date', p."created_date",
      'updated_date', p."updated_date")
    when 'documentation' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_time', p."visit_time",
      'visit_type', p."visit_type",
      'status', p."status",
      'nurse_notes', p."nurse_notes",
      'raw_transcription', p."raw_transcription",
      'vital_signs', p."vital_signs",
      'documentation_source', p."documentation_source",
      'grounding_pending', p."grounding_pending",
      'updated_date', p."updated_date")
    when 'hospitalization_risk' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'nurse_notes', p."nurse_notes",
      'vital_signs', p."vital_signs",
      'updated_date', p."updated_date")
    when 'operations_analytics' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'start_time', p."start_time",
      'end_time', p."end_time",
      'created_by', p."created_by",
      'created_date', p."created_date",
      'updated_date', p."updated_date")
    when 'reporting' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'start_time', p."start_time",
      'end_time', p."end_time",
      'nurse_notes', p."nurse_notes",
      'vital_signs', p."vital_signs",
      'created_by', p."created_by",
      'created_date', p."created_date",
      'updated_date', p."updated_date")
    when 'schedule' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_time', p."visit_time",
      'visit_type', p."visit_type",
      'status', p."status",
      'start_time', p."start_time",
      'end_time', p."end_time",
      'updated_date', p."updated_date")
    when 'vitals_trend' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'vital_signs', p."vital_signs",
      'updated_date', p."updated_date")
    else null end
$policy$;

-- From `base44/functions/getAuthorizedVisit/entry.ts`: 3 purposes.
create function "pennsync_records"."visit_exact_purpose_known"(p_purpose text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'compliance_review' then true
    when 'documentation' then true
    when 'schedule' then true
    else false end
$policy$;

create function "pennsync_records"."visit_exact_purpose_admits"(p_purpose text, p_role text) returns boolean
  language sql immutable set search_path = '' as $policy$
  select case p_purpose
    when 'compliance_review' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'documentation' then p_role in ('agency_admin', 'clinician', 'manager')
    when 'schedule' then p_role in ('agency_admin', 'clinician', 'manager')
    else false end
$policy$;

-- Stable rather than immutable: a date or timestamp reaches JSON through the
-- session's DateStyle and TimeZone, so this is not constant-foldable.
create function "pennsync_records"."visit_exact_purpose_row"(
  p_purpose text, p "pennsync_records"."visit") returns jsonb
  language sql stable set search_path = '' as $policy$
  select case p_purpose
    when 'compliance_review' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_type', p."visit_type",
      'status', p."status",
      'compliance_score', p."compliance_score",
      'compliance_issues', p."compliance_issues",
      'homebound_status_verified', p."homebound_status_verified",
      'skilled_intervention_documented', p."skilled_intervention_documented",
      'homebound_justification', p."homebound_justification",
      'ai_tags', p."ai_tags",
      'emr_handoff_status', p."emr_handoff_status",
      'documentation_review_ack', p."documentation_review_ack",
      'updated_date', p."updated_date")
    when 'documentation' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_time', p."visit_time",
      'visit_type', p."visit_type",
      'status', p."status",
      'nurse_notes', p."nurse_notes",
      'raw_transcription', p."raw_transcription",
      'vital_signs', p."vital_signs",
      'documentation_source', p."documentation_source",
      'grounding_pending', p."grounding_pending",
      'emr_handoff_status', p."emr_handoff_status",
      'emr_handoff_history', p."emr_handoff_history",
      'documentation_review_ack', p."documentation_review_ack",
      'updated_date', p."updated_date")
    when 'schedule' then jsonb_build_object(
      'id', p."id",
      'patient_id', p."patient_id",
      'visit_date', p."visit_date",
      'visit_time', p."visit_time",
      'visit_type', p."visit_type",
      'status', p."status",
      'start_time', p."start_time",
      'end_time', p."end_time",
      'updated_date', p."updated_date")
    else null end
$policy$;

-- The fields a client may supply to `createAuthorizedVisit`
-- (5 of the 9 its `CLIENT_VISIT_FIELDS` declares; the other
-- 4 are the contract's to decide, and it refuses a payload naming one).
create function "pennsync_records"."visit_create_writable"(p_field text) returns boolean
  language sql immutable set search_path = '' as $write$
  select p_field in ('visit_date', 'visit_time', 'visit_type', 'start_time', 'end_time')
$write$;

create function "pennsync_records"."visit_create_reserved"(p_field text) returns boolean
  language sql immutable set search_path = '' as $write$
  select p_field in ('agency_id', 'client_request_id', 'patient_id', 'status')
$write$;

-- The actions `updateAuthorizedVisit` declares (9), and the
-- 4 this port serves. An action it does not serve is KNOWN and refused with
-- the reason below, which is not the same answer as an action that does not
-- exist — and the generator refuses to render if one is neither.
create function "pennsync_records"."visit_action_known"(p_action text) returns boolean
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'save_documentation' then true
    when 'reschedule' then true
    when 'set_ai_tags' then true
    when 'advance_handoff' then true
    when 'set_review_ack' then true
    when 'read_ai_processing_source' then true
    when 'claim_ai_processing' then true
    when 'publish_ai_processing' then true
    when 'legacy_recovery' then true
    else false end
$action$;

create function "pennsync_records"."visit_action_served"(p_action text) returns boolean
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'save_documentation' then true
    when 'reschedule' then true
    when 'set_ai_tags' then false
    when 'advance_handoff' then true
    when 'set_review_ack' then true
    when 'read_ai_processing_source' then false
    when 'claim_ai_processing' then false
    when 'publish_ai_processing' then false
    when 'legacy_recovery' then false
    else false end
$action$;

-- Why an action is not served. A reason rather than a flag, because "not
-- ported" and "not allowed" are different things to be told.
create function "pennsync_records"."visit_action_unported"(p_action text) returns text
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'save_documentation' then null::text
    when 'reschedule' then null::text
    when 'set_ai_tags' then 'D14 and D22 removed the platform tier, and the original admits nobody else: `requireActionPolicy` requires `user.role === ''admin''` AND the configured SUPER_ADMIN_EMAIL. Dropping that tier closes the action outright, so who may set an AI tag is a decision rather than a rendering detail.'
    when 'advance_handoff' then null::text
    when 'set_review_ack' then null::text
    when 'read_ai_processing_source' then 'Server-to-server only, behind INTERNAL_FN_SECRET. Its one caller is `processCompletedVisit`, which is not ported, and the record store has no concept of a service identity yet.'
    when 'claim_ai_processing' then 'Server-to-server only, behind INTERNAL_FN_SECRET.'
    when 'publish_ai_processing' then 'Server-to-server only, behind INTERNAL_FN_SECRET.'
    when 'legacy_recovery' then 'Paused at source. The original answers 503 before reading anything, deliberately, until an owner-approved recovery protocol exists; porting it would be re-enabling it.'
    else null::text end
$action$;

-- The inputs a served action accepts. Inputs, not columns: `advance_handoff`
-- accepts `next_status` and writes `emr_handoff_status` and its history, and
-- which columns move is the contract's to decide from the action's own logic.
create function "pennsync_records"."visit_action_accepts"(p_action text, p_field text) returns boolean
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'save_documentation' then p_field in ('patient_id', 'status', 'nurse_notes', 'raw_transcription', 'vital_signs', 'compliance_score', 'compliance_issues', 'homebound_status_verified', 'skilled_intervention_documented', 'homebound_justification', 'documentation_source', 'grounding_pending', 'ai_tags')
    when 'reschedule' then p_field in ('visit_time')
    when 'set_ai_tags' then false
    when 'advance_handoff' then p_field in ('next_status')
    when 'set_review_ack' then p_field in ('acknowledged', 'nurse_edited', 'expected_note_hash')
    when 'read_ai_processing_source' then false
    when 'claim_ai_processing' then false
    when 'publish_ai_processing' then false
    when 'legacy_recovery' then false
    else false end
$action$;

-- Declaration order, so an answer does not depend on how a caller spelled it.
create function "pennsync_records"."visit_action_rank"(p_action text) returns integer
  language sql immutable set search_path = '' as $action$
  select case p_action
    when 'save_documentation' then 1
    when 'reschedule' then 2
    when 'set_ai_tags' then 3
    when 'advance_handoff' then 4
    when 'set_review_ack' then 5
    when 'read_ai_processing_source' then 6
    when 'claim_ai_processing' then 7
    when 'publish_ai_processing' then 8
    when 'legacy_recovery' then 9
    else null end
$action$;

reset role;

-- No caller role may ask a policy anything. The contracts are the only way in.
revoke all on function "pennsync_records"."visit_list_purpose_known"(text),
  "pennsync_records"."visit_list_purpose_admits"(text,text),
  "pennsync_records"."visit_list_purpose_page_size"(text),
  "pennsync_records"."visit_list_purpose_row"(text,"pennsync_records"."visit"),
  "pennsync_records"."visit_exact_purpose_known"(text),
  "pennsync_records"."visit_exact_purpose_admits"(text,text),
  "pennsync_records"."visit_exact_purpose_row"(text,"pennsync_records"."visit"),
  "pennsync_records"."visit_create_writable"(text),
  "pennsync_records"."visit_create_reserved"(text),
  "pennsync_records"."visit_action_known"(text),
  "pennsync_records"."visit_action_served"(text),
  "pennsync_records"."visit_action_unported"(text),
  "pennsync_records"."visit_action_accepts"(text,text),
  "pennsync_records"."visit_action_rank"(text)
  from public, anon, authenticated, service_role;

commit;
