// CareMetric AI Branding Utilities

export const BRANDING = {
  name: 'CareMetric AI',
  tagline: 'AI-Powered Clinical Documentation & Care Management',
  logo_url: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/694ec16e72e01b60d22f7cbf/4cdbb3c5a_EB4F3981-36F5-46A4-8E0C-4B53A58EAE88.jpeg',
  colors: {
    primary: '#2563eb',
    secondary: '#3b82f6',
    accent: '#6366f1'
  }
};

/**
 * Generate HTML email template with CareMetric branding
 */
export const generateEmailTemplate = (content, options = {}) => {
  const {
    subject = 'CareMetric AI',
    showLogo = true,
    includeFooter = true
  } = options;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f4f4f4; }
    .container { max-width: 600px; margin: 20px auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, ${BRANDING.colors.primary} 0%, ${BRANDING.colors.secondary} 100%); padding: 30px 20px; text-align: center; }
    .logo { max-width: 80px; height: 80px; border-radius: 12px; background: white; padding: 5px; margin-bottom: 15px; }
    .header-title { color: white; font-size: 24px; font-weight: bold; margin: 0; }
    .header-tagline { color: rgba(255,255,255,0.9); font-size: 14px; margin: 5px 0 0 0; }
    .content { padding: 30px 20px; }
    .footer { background: #f8f9fa; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
    .footer-logo { max-width: 40px; height: 40px; border-radius: 6px; margin-bottom: 10px; }
    .button { display: inline-block; padding: 12px 24px; background: ${BRANDING.colors.primary}; color: white; text-decoration: none; border-radius: 6px; margin: 15px 0; }
  </style>
</head>
<body>
  <div class="container">
    ${showLogo ? `
    <div class="header">
      <img src="${BRANDING.logo_url}" alt="CareMetric AI Logo" class="logo" />
      <h1 class="header-title">${BRANDING.name}</h1>
      <p class="header-tagline">${BRANDING.tagline}</p>
    </div>
    ` : ''}
    
    <div class="content">
      ${content}
    </div>
    
    ${includeFooter ? `
    <div class="footer">
      <img src="${BRANDING.logo_url}" alt="CareMetric AI" class="footer-logo" />
      <p><strong>${BRANDING.name}</strong></p>
      <p>${BRANDING.tagline}</p>
      <p style="margin-top: 15px;">This is an automated message from your CareMetric AI clinical documentation system.</p>
    </div>
    ` : ''}
  </div>
</body>
</html>
  `.trim();
};

/**
 * Generate PDF header with CareMetric branding
 */
export const generatePDFHeader = () => {
  return {
    html: `
      <div style="text-align: center; padding: 20px; border-bottom: 2px solid ${BRANDING.colors.primary};">
        <img src="${BRANDING.logo_url}" style="width: 60px; height: 60px; border-radius: 8px; margin-bottom: 10px;" />
        <h1 style="color: ${BRANDING.colors.primary}; margin: 5px 0; font-size: 22px;">${BRANDING.name}</h1>
        <p style="color: #6b7280; margin: 0; font-size: 12px;">${BRANDING.tagline}</p>
      </div>
    `
  };
};

/**
 * Generate PDF footer with CareMetric branding
 */
export const generatePDFFooter = (options = {}) => {
  const { includePageNumbers = true, customText = '' } = options;
  
  return {
    html: `
      <div style="text-align: center; padding: 15px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #6b7280;">
        <p style="margin: 0;">${customText || `Generated by ${BRANDING.name} - ${BRANDING.tagline}`}</p>
        ${includePageNumbers ? '<p style="margin: 5px 0 0 0;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></p>' : ''}
      </div>
    `
  };
};

/**
 * Format plain text document with CareMetric header
 */
export const formatTextDocument = (content, options = {}) => {
  const { title = '', date = new Date().toLocaleDateString() } = options;
  
  return `
╔════════════════════════════════════════════════════════════╗
║                      CAREMETRIC AI                         ║
║        AI-Powered Clinical Documentation System            ║
╚════════════════════════════════════════════════════════════╝

${title ? `DOCUMENT: ${title}\n` : ''}DATE GENERATED: ${date}

────────────────────────────────────────────────────────────

${content}

────────────────────────────────────────────────────────────
Generated by CareMetric AI
${BRANDING.tagline}
  `.trim();
};

export default BRANDING;